// Auto-generated by scripts/extract-page-copy.mjs (lang: sv)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'När du ska åka till Lappland, månad för månad | LaplandStays',
    description: 'Norrskenssäsong sep–apr, skidtopp jan–mar, midnattssol jun–jul. Guide månad för månad till Lappland: när boenden blir slutbokade, dagsljus och budget.',
  },
  ui: {
    eyebrow: 'Planering',
    h1: 'När du ska åka',
    heroAlt: 'Höstens ruskafärger på Lapplands fjäll, röda och gyllene sluttningar kring en mörkblå sjö',
    lead: 'Den riktiga Lapplandskalendern: när norrskenet kommer, när backarna håller snö och när allt är slutbokat.',
    seasonsEyebrow: 'Fyra överlappande årstider',
    seasonsH2: 'Välj resan du kom för',
    monthEyebrow: 'Månad för månad',
    monthH2: 'Lapplandskalendern',
    monthLead: 'Dagsljustimmar, norrskensfrekvens, snöläge och verkligheten kring bokningsfönstret för varje månad. Dagsljussiffrorna gäller Rovaniemi (66,5° N), Saariselkä och Inari är mörkare på vintern och ljusare på sommaren.',
    th: { month: 'Månad', daylight: 'Dagsljus', aurora: 'Norrsken', snow: 'Snö', vibe: 'Känsla', booking: 'Bokning', from: 'Från' },
    secretEyebrow: 'Om du får välja en månad',
    secretH2: 'Mars är hemligheten',
    secretIntro: 'De flesta norrskensresenärer kommer i december–januari, för då är dagarna som mörkast. Men mars är månaden då de som varit här förr bokar om. Så här ser räknestycket ut:',
    bullets: [
      '11 timmars mörker, 13 timmars dagsljus, natten är lång nog för norrskensfönster, dagen lång nog för skidor och safari utan pannlampa.',
      'Den kallaste snön ligger kvar, största snödjupet i Levi, Ylläs, Saariselkä. Solen värmer upp till −5 °C, inte −30 °C.',
      'Norrskensfönstren är fortfarande aktiva, norrskensovalen är som mest aktiv kring vårdagjämningen. Mars är statistiskt en av de bästa månaderna för norrskensfrekvens.',
      'Betydligt billigare, de flesta boenden ligger klart under jul- och nyårspriserna, och februaris sportlov är redan passerat.',
    ],
    bulletStrong: ['11 timmars mörker, 13 timmars dagsljus', 'Den kallaste snön ligger kvar', 'Norrskensfönstren är fortfarande aktiva', 'Betydligt billigare'],
    catch: 'Haken: påskveckan (mars eller april beroende på år) blir slutbokad, finska inrikesresenärer fyller stugorna. Sikta på de tre första veckorna i mars om du kan.',
    ctaH2: 'Välj din månad, lås datumen',
    ctaLead: 'Glasiglorna på Kakslauttanen och Levin Iglut bokas 8–12 månader i förväg. Påskveckan hos Lapland Hotels fylls 6 månader i förväg. Ju tidigare du bestämmer månad, desto större är utbudet.',
    ctaPrimary: 'Se priser i Lappland',
    ctaSecondary: 'Utforska boendetyper',
    months: [
      { m: 'September', daylight: '13 → 11 h', aurora: 'Första fönstren · syns klara nätter', snow: 'Ruska-höstfärger, ingen snö än', vibe: 'Lugnaste norrskensmånaden, före ruschen', bookingNote: 'Ledigt hos alla boenden' },
      { m: 'Oktober', daylight: '11 → 8 h', aurora: 'Ofta synligt klara nätter', snow: 'Första snön i slutet av månaden', vibe: 'Sen ruska, tidigt norrsken', bookingNote: 'Bästa pris–norrsken-förhållandet under säsongen' },
      { m: 'November', daylight: '7 → 3 h', aurora: 'Ofta klara nätter · mörkaste himlen', snow: 'Bestående snötäcke från mitten av månaden', vibe: 'De mörkaste veckorna börjar, FIS Levi öppnar världscupen', bookingNote: 'Glasiglorna börjar fyllas inför nästa års topp' },
      { m: 'December', daylight: '2–4 h, lång blå skymning', aurora: 'Ofta klara nätter', snow: 'Snö som på ett julkort', vibe: 'Julsäsong, jultomten, familjeresenärer', bookingNote: 'Julveckan bokas 12 mån i förväg' },
      { m: 'Januari', daylight: '4 → 7 h', aurora: 'Ofta synligt · kallast, klarast', snow: 'Djupaste snön', vibe: 'Äkta arktiskt, ner till −30 °C i inlandet', bookingNote: 'Nyårsveckan bokas 10 mån i förväg' },
      { m: 'Februari', daylight: '7 → 11 h', aurora: 'Ofta klara nätter', snow: 'Största snödjupet', vibe: 'Sportlov, den mest familjetäta månaden', bookingNote: 'Sportlovet i mitten av februari är slutbokat 6–8 mån i förväg' },
      { m: 'Mars', daylight: '11 → 13 h', aurora: 'Fortfarande ofta · långa mörka kvällar', snow: 'Fortfarande djup snö, soliga dagar', vibe: 'Den hemliga månaden, ljus, snö, norrsken, mindre trängsel', bookingNote: 'Bäst bevarade hemligheten. Bokas 4–6 mån i förväg' },
      { m: 'April', daylight: '13 → 17 h', aurora: 'Avtar · nätterna för ljusa i slutet av månaden', snow: 'Töar i Rovaniemi, håller i norr', vibe: 'Påskskidor och norrsken, sedan snösmältning', bookingNote: 'Påskveckan slutbokas, resten av månaden är lugn' },
      { m: 'Maj', daylight: '17 → 21 h', aurora: 'I princip inget', snow: 'Mestadels borta utom i fjällen i norr', vibe: 'Mellansäsong, ingen snö, ingen midnattssol än', bookingNote: 'Billigaste månaden att besöka' },
      { m: 'Juni', daylight: '24 h midnattssol', aurora: 'Omöjligt (solen går aldrig ner)', snow: 'Ingen söder om fjällen', vibe: 'Midnattssol, vandring, fiske, inga insekter än', bookingNote: 'Gott om plats fram till midsommarveckan' },
      { m: 'Juli', daylight: '24 h, sedan 22 h', aurora: 'Omöjligt', snow: 'Ingen', vibe: 'Högsommar, mygg i inlandet, badsjöar', bookingNote: 'Finska inrikesresenärer fyller stugorna' },
      { m: 'Augusti', daylight: '22 → 16 h', aurora: 'Sista veckan, de första fönstren återvänder', snow: 'Ingen', vibe: 'Sensommar, ruska börjar i slutet av månaden', bookingNote: 'Ledigt utbud, sista lugnet före norrskenssäsongen' },
    ],
    seasonCards: [
      { title: 'Norrskenstopp, nov till mars', body: 'Mörkast, kallast, mest konsekvent. Norrsken syns de flesta klara nätter. Slutbokas 6–12 månader i förväg hos de kända glasiglo-boendena.' },
      { title: 'Skidsäsong, dec till april', body: 'Levi öppnar med FIS-slalomen i november. Säkert snötäcke dec–mars. Påskveckan är den sista pålitliga skidveckan, april är snösmältning i söder medan fjällen håller i norr.' },
      { title: 'Midnattssol, juni till mitten av juli', body: 'Dygnet runt-ljus norr om polcirkeln. Inget norrsken möjligt. Lugnt utbud, lägre priser, finska inrikesresenärer i stugorna.' },
      { title: 'Ruska, slutet av augusti till början av oktober', body: 'Höstfärgsveckorna. Björkar och rönn i rött och guld. De första norrskensfönstren återvänder i mitten av september. Årets bästa förhållande mellan pris och upplevelse.' },
    ],
  },
}

export default copy
