// Auto-generated by scripts/extract-page-copy.mjs (lang: fi)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Milloin Lappiin, kuukausi kuukaudelta | LaplandStays',
    description: 'Revontulet syys–huhtikuussa, hiihto tammi–maaliskuussa, keskiyön aurinko kesä–heinäkuussa. Kuukausiopas Lappiin: milloin kohteet täyttyvät, valo, budjetti.',
  },
  ui: {
    eyebrow: 'Suunnittelu',
    h1: 'Milloin matkustaa',
    heroAlt: 'Ruskan värit Lapin tuntureilla, punaiset ja kullanväriset rinteet tummansinisen järven ympärillä',
    lead: 'Aito Lapin kalenteri: milloin revontulet syttyvät, milloin rinteet pitävät lunta ja milloin kaikki on jo varattu.',
    seasonsEyebrow: 'Neljä päällekkäistä sesonkia',
    seasonsH2: 'Valitse matkasi tarkoitus',
    monthEyebrow: 'Kuukausi kuukaudelta',
    monthH2: 'Lapin kalenteri',
    monthLead: 'Päivänvalon tunnit, revontulitaajuus, lumitilanne ja varausikkunan todellisuus kullekin kuukaudelle. Päivänvaloluvut Rovaniemelle (66,5° N), Saariselkä ja Inari ovat pimeämpiä talvella ja vaaleampia kesällä.',
    th: { month: 'Kuukausi', daylight: 'Päivänvalo', aurora: 'Revontulet', snow: 'Lumi', vibe: 'Tunnelma', booking: 'Varaus', from: 'Alkaen' },
    secretEyebrow: 'Jos voit valita yhden kuukauden',
    secretH2: 'Maaliskuu on salaisuus',
    secretIntro: 'Useimmat revontulimatkailijat tulevat joulu–tammikuussa koska silloin päivät ovat pimeimmät. Mutta maaliskuu on kuukausi jolloin aikaisemmat kävijät varaavat uudelleen. Tässä matematiikka:',
    bullets: [
      '11 tuntia pimeyttä, 13 tuntia päivänvaloa, riittävän pitkä yö revontuli-ikkunoille, riittävän pitkä päivä hiihtoon ja safariin ilman otsalamppua.',
      'Kylmin lumi vielä maassa, huippusyvyys Levillä, Ylläksellä, Saariselällä. Aurinko lämmittää −5 °C:een, ei −30 °C:een.',
      'Revontuli-ikkunat vielä aktiiviset, aurora-ovaali on aktiivisimmillaan kevätpäiväntasauksen aikoihin. Maaliskuu on tilastollisesti yksi parhaista revontulikuukausista.',
      'Huomattavasti edullisempi, useimmat kohteet laskevat hintojaan selvästi joulun/uudenvuoden tasosta, helmikuun koululomat jo takana.',
    ],
    bulletStrong: ['11 tuntia pimeyttä, 13 tuntia päivänvaloa', 'Kylmin lumi vielä maassa', 'Revontuli-ikkunat vielä aktiiviset', 'Huomattavasti edullisempi'],
    catch: 'Saalis: Pääsiäisviikko (maalis/huhtikuu vuodesta riippuen) menee täyteen, kotimainen matkailu täyttää mökit. Tavoittele maaliskuun kolmea ensimmäistä viikkoa jos voit.',
    ctaH2: 'Valitse kuukausi, lukitse päivät',
    ctaLead: 'Kakslauttasen ja Levin Iglutin lasi-iglut varataan 8–12 kuukautta etukäteen. Pääsiäisviikko Lapland Hotelsissa menee täyteen 6 kuukautta etukäteen. Mitä aiemmin päätät kuukauden, sitä laajempi tarjonta.',
    ctaPrimary: 'Katso Lapin hinnat',
    ctaSecondary: 'Selaa majoitustyyppejä',
    months: [
      { m: 'Syyskuu', daylight: '13 → 11 h', aurora: 'Ensimmäiset ikkunat · näkyvät selkeinä öinä', snow: 'Ruska, ei vielä lunta', vibe: 'Hiljaisin revontulikuukausi, ohita ruuhka', bookingNote: 'Avoin tarjonta kaikissa kohteissa' },
      { m: 'Lokakuu', daylight: '11 → 8 h', aurora: 'Usein näkyvissä selkeinä öinä', snow: 'Ensilumi kuun lopussa', vibe: 'Loppuruska, varhaiset revontulet', bookingNote: 'Sesongin paras hinta-revontuli-suhde' },
      { m: 'Marraskuu', daylight: '7 → 3 h', aurora: 'Usein näkyvissä selkeinä öinä · pimein taivas', snow: 'Pysyvä lumipeite kuun puolivälistä', vibe: 'Kaamos alkaa, FIS Levi avaa maailmancupin', bookingNote: 'Lasi-iglut alkavat täyttyä seuraavan vuoden huipulle' },
      { m: 'Joulukuu', daylight: '2–4 h, "kaamos"', aurora: 'Usein näkyvissä selkeinä öinä', snow: 'Joulukortti-lumi', vibe: 'Joulu, Joulupukki, perheet', bookingNote: 'Jouluviikko varataan 12 kk etukäteen' },
      { m: 'Tammikuu', daylight: '4 → 7 h', aurora: 'Usein näkyvissä · kylmin, selkein', snow: 'Syvin lumi', vibe: 'Aito arktinen, −30 °C sisämaassa', bookingNote: 'Uudenvuodenviikko 10 kk etukäteen' },
      { m: 'Helmikuu', daylight: '7 → 11 h', aurora: 'Usein näkyvissä selkeinä öinä', snow: 'Huippusyvyys', vibe: 'Koululomat, perhematkailijoiden ruuhkaisin kuukausi', bookingNote: 'Helmikuun talvilomaviikko 6–8 kk etukäteen' },
      { m: 'Maaliskuu', daylight: '11 → 13 h', aurora: 'Yhä aktiiviset · pitkät pimeät illat', snow: 'Vielä syvä, aurinkoiset päivät', vibe: 'Salainen kuukausi, valo, lumi, revontulet, vähemmän väkeä', bookingNote: 'Paras salaisuus. Varataan 4–6 kk etukäteen' },
      { m: 'Huhtikuu', daylight: '13 → 17 h', aurora: 'Hiipuvat · yöt liian valoisia kuun lopussa', snow: 'Sulaa Rovaniemellä, pohjoisessa pysyy', vibe: 'Pääsiäishiihto + revontulet, sitten sulaminen', bookingNote: 'Pääsiäisviikko täyteen, muu kuukausi rauhallinen' },
      { m: 'Toukokuu', daylight: '17 → 21 h', aurora: 'Käytännössä ei lainkaan', snow: 'Pääosin sulanut paitsi pohjoisen tuntureilla', vibe: 'Välikuukausi, ei lunta, ei vielä keskiyön aurinkoa', bookingNote: 'Halvin kuukausi käydä' },
      { m: 'Kesäkuu', daylight: '24 h keskiyön aurinko', aurora: 'Mahdotonta (aurinko ei laske)', snow: 'Ei lunta etelässä tunturilta', vibe: 'Keskiyön aurinko, patikointi, kalastus, ei hyttysiä vielä', bookingNote: 'Avoin saatavuus juhannukseen asti' },
      { m: 'Heinäkuu', daylight: '24 h, sitten 22 h', aurora: 'Mahdotonta', snow: 'Ei', vibe: 'Kesän huippu, hyttysiä sisämaassa, rantajärvet', bookingNote: 'Suomalaiset täyttävät mökit' },
      { m: 'Elokuu', daylight: '22 → 16 h', aurora: 'Viimeinen viikko, ensimmäiset ikkunat palaavat', snow: 'Ei', vibe: 'Loppukesä, ruska alkaa kuun lopussa', bookingNote: 'Avoin tarjonta, viimeinen rauha ennen revontulisesonkia' },
    ],
    seasonCards: [
      { title: 'Revontuli-huippu, marraskuu–maaliskuu', body: 'Pimein, kylmin, tasaisin. Revontulet näkyvät useimpina selkeinä öinä. Varataan 6–12 kk etukäteen nimetyissä lasi-iglu-kohteissa.' },
      { title: 'Hiihtokausi, joulukuu–huhtikuu', body: 'Levi avaa FIS-pujottelulla marraskuussa. Luotettava lumipeite joulu–maaliskuussa. Pääsiäisviikko on viimeinen luotettava hiihtoviikko, huhtikuu sulattaa etelässä, tunturit pohjoisessa pitävät.' },
      { title: 'Keskiyön aurinko, kesäkuusta heinäkuun puoliväliin', body: '24 tunnin päivänvalo napapiirin pohjoispuolella. Revontulet eivät ole mahdollisia. Rauhallinen tarjonta, edullisemmat hinnat, suomalaiset matkailijat mökeissä.' },
      { title: 'Ruska, elokuun lopusta lokakuun alkuun', body: 'Syksyn väriviikot. Koivut ja pihlajat punaisina ja kultaisina. Ensimmäiset revontuli-ikkunat palaavat syyskuun puolivälissä. Vuoden paras hinta-elämys-suhde.' },
    ],
  },
}

export default copy
