// Auto-generated by scripts/extract-page-copy.mjs (lang: it)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Quando partire in Lapponia, mese per mese | LaplandStays',
    description: 'Aurore set–apr, sci gen–mar, sole di mezzanotte giu–lug. Guida mese per mese della Lapponia: quando gli alloggi sono pieni, ore di luce e budget.',
  },
  ui: {
    eyebrow: 'Pianificazione',
    h1: 'Quando partire',
    heroAlt: 'Colori autunnali della ruska sui fell della Lapponia, pendii rossi e dorati attorno a un lago blu scuro',
    lead: "Il vero calendario della Lapponia: quando appare l'aurora, quando le piste tengono la neve e quando tutto è esaurito.",
    seasonsEyebrow: 'Quattro stagioni che si sovrappongono',
    seasonsH2: 'Scelga il viaggio che è venuto a cercare',
    monthEyebrow: 'Mese per mese',
    monthH2: 'Il calendario della Lapponia',
    monthLead: 'Ore di luce, frequenza delle aurore, stato della neve e realtà della finestra di prenotazione per ogni mese. Le ore di luce sono riferite a Rovaniemi (66,5° N), Saariselkä e Inari sono più scure in inverno e più luminose in estate.',
    th: { month: 'Mese', daylight: 'Luce', aurora: 'Aurore', snow: 'Neve', vibe: 'Atmosfera', booking: 'Prenotazione', from: 'Da' },
    secretEyebrow: 'Se può scegliere un solo mese',
    secretH2: 'Marzo è il segreto',
    secretIntro: 'Quasi tutti i viaggiatori aurora arrivano tra dicembre e gennaio perché in quel periodo le giornate sono più scure. Ma il mese in cui chi è già venuto torna a prenotare è marzo. Il conto è questo:',
    bullets: [
      '11 ore di buio, 13 ore di luce, notte sufficiente per le finestre aurora, giornata sufficiente per sci e safari senza lampada frontale.',
      'La neve più fredda è ancora lì, massima profondità a Levi, Ylläs, Saariselkä. Il sole porta la temperatura a −5 °C, non −30 °C.',
      'Le finestre aurora sono ancora attive, l\'ovale aurorale è più attivo intorno all\'equinozio di primavera. Marzo è statisticamente uno dei mesi migliori per frequenza.',
      'Decisamente più economico, molti alloggi calano nettamente rispetto a Natale/Capodanno e le vacanze scolastiche di febbraio sono già passate.',
    ],
    bulletStrong: ['11 ore di buio, 13 ore di luce', 'La neve più fredda è ancora lì', 'Le finestre aurora sono ancora attive', 'Decisamente più economico'],
    catch: 'L\'inghippo: la settimana di Pasqua (marzo o aprile a seconda dell\'anno) va esaurita, il turismo interno finlandese riempie i cottage. Punti alle prime tre settimane di marzo, se può.',
    ctaH2: 'Scelga il mese, blocchi le date',
    ctaLead: 'Gli igloo di vetro di Kakslauttanen e di Levin Iglut si prenotano con 8–12 mesi di anticipo. La settimana di Pasqua nei Lapland Hotels va esaurita 6 mesi prima. Prima decide il mese, più ampia è la scelta.',
    ctaPrimary: 'Vedi i prezzi in Lapponia',
    ctaSecondary: 'Sfoglia i tipi di alloggio',
    months: [
      { m: 'Settembre', daylight: '13 → 11 h', aurora: 'Prime finestre · visibili nelle notti serene', snow: 'Colori ruska, ancora niente neve', vibe: 'Il mese aurora più tranquillo, eviti la calca', bookingNote: 'Disponibilità aperta ovunque' },
      { m: 'Ottobre', daylight: '11 → 8 h', aurora: 'Apparizioni frequenti nelle notti serene', snow: 'Prima neve a fine mese', vibe: 'Tardo ruska, aurore in anticipo', bookingNote: 'Miglior rapporto prezzo/aurore della stagione' },
      { m: 'Novembre', daylight: '7 → 3 h', aurora: 'Frequenti nelle notti serene · cielo più scuro', snow: 'Manto permanente da metà mese', vibe: 'Iniziano le settimane più buie, FIS Levi apre la Coppa del Mondo', bookingNote: 'Gli igloo di vetro iniziano a riempirsi per il picco dell\'anno dopo' },
      { m: 'Dicembre', daylight: '2–4 h, lungo crepuscolo blu', aurora: 'Frequenti nelle notti serene', snow: 'Neve da cartolina', vibe: 'Stagione natalizia, Babbo Natale, famiglie', bookingNote: 'La settimana di Natale si prenota 12 mesi prima' },
      { m: 'Gennaio', daylight: '4 → 7 h', aurora: 'Frequenti · più freddo, più limpido', snow: 'Neve più profonda', vibe: 'Vero artico, −30 °C nell\'entroterra', bookingNote: 'La settimana di Capodanno si prenota 10 mesi prima' },
      { m: 'Febbraio', daylight: '7 → 11 h', aurora: 'Frequenti nelle notti serene', snow: 'Massima profondità', vibe: 'Vacanze scolastiche, il mese più affollato di famiglie', bookingNote: 'La metà di febbraio si esaurisce 6–8 mesi prima' },
      { m: 'Marzo', daylight: '11 → 13 h', aurora: 'Ancora frequenti · lunghe serate buie', snow: 'Ancora profonda, giornate di sole', vibe: 'Il mese segreto, luce, neve, aurore, meno gente', bookingNote: 'Il segreto meglio custodito. Si prenota 4–6 mesi prima' },
      { m: 'Aprile', daylight: '13 → 17 h', aurora: 'In calo · notti troppo chiare a fine mese', snow: 'Disgelo a Rovaniemi, tiene a nord', vibe: 'Sci pasquale + aurore, poi disgelo', bookingNote: 'Settimana di Pasqua esaurita, il resto del mese calmo' },
      { m: 'Maggio', daylight: '17 → 21 h', aurora: 'Praticamente nessuna', snow: 'Sparita quasi ovunque, salvo le fjell del nord', vibe: 'Mese di passaggio, niente neve, ancora niente sole di mezzanotte', bookingNote: 'Il mese più economico' },
      { m: 'Giugno', daylight: '24 h, sole di mezzanotte', aurora: 'Impossibile (il sole non tramonta)', snow: 'Nessuna a sud delle fjell', vibe: 'Sole di mezzanotte, trekking, pesca, niente zanzare ancora', bookingNote: 'Disponibilità aperta fino alla settimana di mezza estate' },
      { m: 'Luglio', daylight: '24 h poi 22 h', aurora: 'Impossibile', snow: 'Nessuna', vibe: 'Piena estate, zanzare nell\'entroterra, laghi balneari', bookingNote: 'I viaggiatori finlandesi riempiono i cottage' },
      { m: 'Agosto', daylight: '22 → 16 h', aurora: 'Ultima settimana, tornano le prime finestre', snow: 'Nessuna', vibe: 'Fine estate, ruska che inizia a fine mese', bookingNote: 'Disponibilità aperta, ultima quiete prima della stagione aurore' },
    ],
    seasonCards: [
      { title: 'Picco aurore, da novembre a marzo', body: 'Più scuro, più freddo, più costante. Aurora visibile nella maggior parte delle notti serene. Negli igloo di vetro più noti si esaurisce con 6–12 mesi di anticipo.' },
      { title: 'Stagione sciistica, da dicembre ad aprile', body: 'Levi apre con lo slalom FIS a novembre. Manto affidabile da dicembre a marzo. La settimana di Pasqua è l\'ultima settimana sciistica affidabile, aprile disgela a sud, le fjell tengono a nord.' },
      { title: 'Sole di mezzanotte, da giugno a metà luglio', body: '24 ore di luce a nord del Circolo Polare. Aurore non possibili. Disponibilità tranquilla, prezzi più bassi, viaggiatori finlandesi nei cottage.' },
      { title: 'Ruska, da fine agosto a inizio ottobre', body: 'Le settimane dei colori autunnali. Betulle e sorbi in rosso e oro. Le prime finestre aurora tornano a metà settembre. Miglior rapporto prezzo/esperienza dell\'anno.' },
    ],
  },
}

export default copy
