// Auto-generated by scripts/extract-page-copy.mjs (lang: nl)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Wanneer naar Lapland, maand voor maand | LaplandStays',
    description: 'Noorderlichtseizoen sep–apr, skipiek jan–mar, middernachtzon jun–jul. Maand-voor-maand-gids voor Lapland: wanneer accommodaties volzitten, daglicht en budget.',
  },
  ui: {
    eyebrow: 'Plannen',
    h1: 'Wanneer gaan',
    heroAlt: 'Herfstkleuren van de ruska op de fjälls van Lapland, rode en gouden hellingen rond een donkerblauw meer',
    lead: 'De echte Lapland-kalender: wanneer het noorderlicht komt, wanneer de pistes sneeuw houden en wanneer alles volgeboekt is.',
    seasonsEyebrow: 'Vier overlappende seizoenen',
    seasonsH2: 'Kies de reis waarvoor u kwam',
    monthEyebrow: 'Maand voor maand',
    monthH2: 'De Lapland-kalender',
    monthLead: 'Daglichturen, noorderlichtfrequentie, sneeuwstatus en de realiteit van het boekvenster per maand. De daglichtcijfers gelden voor Rovaniemi (66,5° N), Saariselkä en Inari zijn in de winter donkerder en in de zomer lichter.',
    th: { month: 'Maand', daylight: 'Daglicht', aurora: 'Noorderlicht', snow: 'Sneeuw', vibe: 'Sfeer', booking: 'Boeking', from: 'Vanaf' },
    secretEyebrow: 'Als u één maand mocht kiezen',
    secretH2: 'Maart is het geheim',
    secretIntro: 'De meeste noorderlichtreizigers komen in december–januari omdat de dagen dan het donkerst zijn. Maar de maand waarin terugkerende reizigers opnieuw boeken, is maart. De rekensom:',
    bullets: [
      '11 uur duisternis, 13 uur daglicht, een nacht lang genoeg voor noorderlichtbuien, een dag lang genoeg voor ski en safari zonder hoofdlamp.',
      'De koudste sneeuw ligt nog steeds, piekdiepte in Levi, Ylläs, Saariselkä. De zon warmt op tot −5 °C, niet −30 °C.',
      'Noorderlichtbuien zijn nog actief, het noorderlicht-ovaal is rond de lente-equinox het meest actief. Maart is statistisch een van de beste noorderlichtmaanden.',
      'Aanzienlijk goedkoper, de meeste accommodaties zakken fors ten opzichte van Kerst/Nieuwjaar; de voorjaarsvakantie van februari is dan al voorbij.',
    ],
    bulletStrong: ['11 uur duisternis, 13 uur daglicht', 'De koudste sneeuw ligt nog steeds', 'Noorderlichtbuien zijn nog actief', 'Aanzienlijk goedkoper'],
    catch: 'De adder: de paasweek (maart of april, afhankelijk van het jaar) raakt vol, Finse binnenlandse reizigers vullen de cabins. Mik op de eerste drie weken van maart als het kan.',
    ctaH2: 'Kies de maand, leg de data vast',
    ctaLead: 'Glasiglo\'s bij Kakslauttanen en Levin Iglut worden 8–12 maanden vooruit geboekt. De paasweek in Lapland Hotels is 6 maanden van tevoren vol. Hoe eerder u de maand kiest, hoe ruimer het aanbod.',
    ctaPrimary: 'Bekijk prijzen in Lapland',
    ctaSecondary: 'Bekijk accommodatietypes',
    months: [
      { m: 'September', daylight: '13 → 11 u', aurora: 'Eerste buien · zichtbaar in heldere nachten', snow: 'Ruska-herfstkleur, nog geen sneeuw', vibe: 'De rustigste noorderlichtmaand, vermijd de drukte', bookingNote: 'Open beschikbaarheid overal' },
      { m: 'Oktober', daylight: '11 → 8 u', aurora: 'Vaak zichtbaar in heldere nachten', snow: 'Eerste sneeuw eind van de maand', vibe: 'Late ruska, vroege noorderlicht', bookingNote: 'Beste prijs-noorderlichtverhouding van het seizoen' },
      { m: 'November', daylight: '7 → 3 u', aurora: 'Vaak zichtbaar in heldere nachten · donkerste hemel', snow: 'Vast sneeuwdek vanaf medio november', vibe: 'De donkerste weken beginnen, FIS Levi opent de Wereldbeker', bookingNote: 'Glasiglo\'s lopen vol voor de piek van volgend jaar' },
      { m: 'December', daylight: '2–4 u, lange blauwe schemering', aurora: 'Vaak zichtbaar in heldere nachten', snow: 'Kerstkaartsneeuw', vibe: 'Kerstseizoen, Kerstman, gezinnen', bookingNote: 'De kerstweek is 12 maanden vooruit volgeboekt' },
      { m: 'Januari', daylight: '4 → 7 u', aurora: 'Vaak zichtbaar · koudst, helderst', snow: 'Diepste sneeuw', vibe: 'Echt arctisch, tot −30 °C in het binnenland', bookingNote: 'Nieuwjaarsweek 10 maanden vooruit' },
      { m: 'Februari', daylight: '7 → 11 u', aurora: 'Vaak zichtbaar in heldere nachten', snow: 'Maximale diepte', vibe: 'Schoolvakanties, drukste gezinsmaand', bookingNote: 'Midden-februari is 6–8 maanden van tevoren uitverkocht' },
      { m: 'Maart', daylight: '11 → 13 u', aurora: 'Nog steeds vaak · lange donkere avonden', snow: 'Nog diep, zonnige dagen', vibe: 'De geheime maand, licht, sneeuw, noorderlicht, minder drukte', bookingNote: 'Best bewaarde geheim. Boekt 4–6 maanden vooruit' },
      { m: 'April', daylight: '13 → 17 u', aurora: 'Neemt af · nachten te licht aan het eind van de maand', snow: 'Smelt in Rovaniemi, houdt stand in het noorden', vibe: 'Paasski + noorderlicht, daarna dooi', bookingNote: 'Paasweek vol, rest van de maand rustig' },
      { m: 'Mei', daylight: '17 → 21 u', aurora: 'Praktisch geen', snow: 'Grotendeels weg, behalve in noordelijke fjälls', vibe: 'Tussenmaand, geen sneeuw, nog geen middernachtzon', bookingNote: 'Goedkoopste maand' },
      { m: 'Juni', daylight: '24 u middernachtzon', aurora: 'Onmogelijk (zon gaat niet onder)', snow: 'Geen, ten zuiden van de fjälls', vibe: 'Middernachtszon, wandelen, vissen, nog geen muggen', bookingNote: 'Open beschikbaarheid tot midzomerweek' },
      { m: 'Juli', daylight: '24 u dan 22 u', aurora: 'Onmogelijk', snow: 'Geen', vibe: 'Hoogzomer, muggen in het binnenland, strandmeren', bookingNote: 'Finse binnenlandse reizigers vullen de cabins' },
      { m: 'Augustus', daylight: '22 → 16 u', aurora: 'Laatste week, eerste buien keren terug', snow: 'Geen', vibe: 'Nazomer, ruska start aan het eind van de maand', bookingNote: 'Open aanbod, laatste rust voor het noorderlichtseizoen' },
    ],
    seasonCards: [
      { title: 'Noorderlichtpiek, november tot maart', body: 'Donkerst, koudst, meest consistent. Noorderlicht zichtbaar in de meeste heldere nachten. Bij toonaangevende glasiglo\'s 6–12 maanden vooruit volgeboekt.' },
      { title: 'Skiseizoen, december tot april', body: 'Levi opent in november met de FIS-slalom. Betrouwbaar sneeuwdek december–maart. Paasweek is de laatste betrouwbare skiweek, april dooit in het zuiden, fjälls houden stand in het noorden.' },
      { title: 'Middernachtszon, juni tot half juli', body: '24 uur daglicht ten noorden van de Poolcirkel. Geen noorderlicht mogelijk. Rustig aanbod, lagere prijzen, Finse binnenlandse reizigers in de cabins.' },
      { title: 'Ruska, eind augustus tot begin oktober', body: 'De herfstkleurweken. Berken en lijsterbessen in rood en goud. Eerste noorderlichtbuien medio september terug. Beste prijs-belevenisverhouding van het jaar.' },
    ],
  },
}

export default copy
