// Auto-generated by scripts/extract-page-copy.mjs (lang: fr)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Quand partir en Laponie, mois par mois | LaplandStays',
    description: 'Aurores sep–avr, ski jan–mar, soleil de minuit juin–juil. Guide mois par mois de la Laponie : quand les hébergements sont complets, heures de jour et budget.',
  },
  ui: {
    eyebrow: 'Planifier',
    h1: 'Quand partir',
    heroAlt: "Couleurs d'automne de la ruska sur les fjells de Laponie, pentes rouges et dorées autour d'un lac bleu foncé",
    lead: "Le vrai calendrier de la Laponie : quand l'aurore apparaît, quand les pistes tiennent la neige et quand tout est complet.",
    seasonsEyebrow: 'Quatre saisons qui se chevauchent',
    seasonsH2: 'Choisissez le voyage que vous êtes venu chercher',
    monthEyebrow: 'Mois par mois',
    monthH2: 'Le calendrier de la Laponie',
    monthLead: 'Heures de jour, fréquence des aurores, état de la neige et réalité de la fenêtre de réservation pour chaque mois. Les heures de jour sont données pour Rovaniemi (66,5° N), Saariselkä et Inari sont plus sombres en hiver et plus lumineux en été.',
    th: { month: 'Mois', daylight: 'Jour', aurora: 'Aurores', snow: 'Neige', vibe: 'Ambiance', booking: 'Réservation', from: 'À partir de' },
    secretEyebrow: 'Si vous deviez n\'en choisir qu\'un',
    secretH2: 'Mars, c\'est le secret',
    secretIntro: 'La plupart des voyageurs aurores viennent en décembre–janvier parce que les jours sont alors les plus sombres. Mais le mois où ceux qui sont déjà venus reviennent, c\'est mars. Le calcul :',
    bullets: [
      '11 heures d\'obscurité, 13 heures de jour, une nuit assez longue pour les fenêtres aurores, une journée assez longue pour le ski et le safari sans frontale.',
      'La neige la plus froide est encore là, épaisseur maximale à Levi, Ylläs, Saariselkä. Le soleil remonte à −5 °C, pas −30 °C.',
      'Les fenêtres aurores sont encore actives, l\'ovale auroral est le plus actif autour de l\'équinoxe de printemps. Mars est statistiquement l\'un des meilleurs mois pour la fréquence des aurores.',
      'Nettement moins cher, la plupart des hébergements baissent fortement par rapport à Noël/Nouvel An, et les vacances scolaires de février sont déjà passées.',
    ],
    bulletStrong: ['11 heures d\'obscurité, 13 heures de jour', 'La neige la plus froide est encore là', 'Les fenêtres aurores sont encore actives', 'Nettement moins cher'],
    catch: 'Le piège : la semaine de Pâques (en mars ou avril selon les années) affiche complet, le tourisme intérieur finlandais remplit les chalets. Visez les trois premières semaines de mars si possible.',
    ctaH2: 'Choisissez votre mois, verrouillez les dates',
    ctaLead: 'Les igloos de verre de Kakslauttanen et de Levin Iglut se réservent 8 à 12 mois à l\'avance. La semaine de Pâques dans les Lapland Hotels affiche complet 6 mois avant. Plus vous décidez tôt du mois, plus l\'offre est large.',
    ctaPrimary: 'Voir les prix en Laponie',
    ctaSecondary: 'Parcourir les types d\'hébergement',
    months: [
      { m: 'Septembre', daylight: '13 → 11 h', aurora: 'Premières fenêtres · visibles par nuit dégagée', snow: 'Couleurs ruska, pas encore de neige', vibe: 'Le mois aurores le plus calme, évitez la foule', bookingNote: 'Disponibilité ouverte partout', fromPrice: '100 €' },
      { m: 'Octobre', daylight: '11 → 8 h', aurora: 'Apparitions fréquentes par nuit dégagée', snow: 'Première neige en fin de mois', vibe: 'Fin ruska, début aurores', bookingNote: 'Meilleur rapport prix/aurores de la saison', fromPrice: '100 €' },
      { m: 'Novembre', daylight: '7 → 3 h', aurora: 'Fréquentes par nuit dégagée · ciel le plus sombre', snow: 'Manteau permanent à partir de la mi-mois', vibe: 'La nuit polaire commence, FIS Levi ouvre la Coupe du monde', bookingNote: 'Les igloos de verre se remplissent pour le pic de l\'année suivante', fromPrice: '150 €' },
      { m: 'Décembre', daylight: '2–4 h, « kaamos » nuit polaire', aurora: 'Fréquentes par nuit dégagée', snow: 'Neige de carte postale', vibe: 'Saison de Noël, le Père Noël, les familles', bookingNote: 'La semaine de Noël se réserve 12 mois à l\'avance', fromPrice: '250 €' },
      { m: 'Janvier', daylight: '4 → 7 h', aurora: 'Fréquentes · le plus froid, le plus clair', snow: 'Neige la plus profonde', vibe: 'Arctique véritable, −30 °C à l\'intérieur des terres', bookingNote: 'Le Nouvel An se réserve 10 mois à l\'avance', fromPrice: '200 €' },
      { m: 'Février', daylight: '7 → 11 h', aurora: 'Fréquentes par nuit dégagée', snow: 'Épaisseur maximale', vibe: 'Vacances scolaires, le mois le plus chargé en familles', bookingNote: 'La mi-février se vend 6 à 8 mois avant', fromPrice: '200 €' },
      { m: 'Mars', daylight: '11 → 13 h', aurora: 'Encore fréquentes · longues soirées sombres', snow: 'Toujours profonde, journées ensoleillées', vibe: 'Le mois secret, lumière, neige, aurores, moins de monde', bookingNote: 'Le secret le mieux gardé. Se réserve 4 à 6 mois avant', fromPrice: '150 €' },
      { m: 'Avril', daylight: '13 → 17 h', aurora: 'En déclin · nuits trop claires en fin de mois', snow: 'Fond à Rovaniemi, tient au nord', vibe: 'Ski de Pâques + aurores, puis dégel', bookingNote: 'Semaine de Pâques complète, reste du mois calme', fromPrice: '120 €' },
      { m: 'Mai', daylight: '17 → 21 h', aurora: 'En pratique aucune', snow: 'Surtout disparue, sauf fjells du nord', vibe: 'Mois charnière, ni neige, ni soleil de minuit', bookingNote: 'Mois le moins cher pour venir', fromPrice: '80 €' },
      { m: 'Juin', daylight: '24 h, soleil de minuit', aurora: 'Impossible (le soleil ne se couche pas)', snow: 'Aucune au sud des fjells', vibe: 'Soleil de minuit, randonnée, pêche, pas encore de moustiques', bookingNote: 'Disponibilité ouverte jusqu\'à la semaine de la Saint-Jean', fromPrice: '100 €' },
      { m: 'Juillet', daylight: '24 h puis 22 h', aurora: 'Impossible', snow: 'Aucune', vibe: 'Plein été, moustiques à l\'intérieur, lacs et plages', bookingNote: 'Les voyageurs finlandais remplissent les chalets', fromPrice: '100 €' },
      { m: 'Août', daylight: '22 → 16 h', aurora: 'Dernière semaine, premières fenêtres', snow: 'Aucune', vibe: 'Fin d\'été, ruska qui démarre en fin de mois', bookingNote: 'Offre ouverte, dernier calme avant la saison aurores', fromPrice: '100 €' },
    ],
    seasonCards: [
      { title: 'Pic aurores, de novembre à mars', body: 'Le plus sombre, le plus froid, le plus régulier. Aurores visibles la plupart des nuits dégagées. Réservations complètes 6 à 12 mois à l\'avance dans les igloos de verre reconnus.' },
      { title: 'Saison de ski, de décembre à avril', body: 'Levi ouvre avec le slalom FIS en novembre. Manteau fiable de décembre à mars. La semaine de Pâques est la dernière semaine de ski fiable, avril fond au sud, les fjells tiennent au nord.' },
      { title: 'Soleil de minuit, de juin à mi-juillet', body: '24 heures de jour au nord du cercle polaire. Aucune aurore possible. Offre calme, prix plus bas, voyageurs intérieurs finlandais dans les chalets.' },
      { title: 'Ruska, de fin août à début octobre', body: 'Les semaines des couleurs d\'automne. Bouleaux et sorbiers en rouge et or. Premières fenêtres aurores de retour mi-septembre. Le meilleur rapport prix/expérience de l\'année.' },
    ],
  },
}

export default copy
