// Auto-generated by scripts/extract-page-copy.mjs (lang: es)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Cuándo ir a Laponia, mes a mes | LaplandStays',
    description: 'Temporada de auroras sep–abr, esquí ene–mar, sol de medianoche jun–jul. Guía mes a mes de Laponia: cuándo se agotan los alojamientos, luz y presupuesto.',
  },
  ui: {
    eyebrow: 'Planificación',
    h1: 'Cuándo ir',
    heroAlt: 'Colores otoñales de la ruska en los fells de Laponia, laderas rojas y doradas alrededor de un lago azul oscuro',
    lead: 'El calendario real de Laponia: cuándo aparece la aurora, cuándo las pistas aguantan la nieve y cuándo todo se agota.',
    seasonsEyebrow: 'Cuatro temporadas que se solapan',
    seasonsH2: 'Elija el viaje al que vino',
    monthEyebrow: 'Mes a mes',
    monthH2: 'El calendario de Laponia',
    monthLead: 'Horas de luz, frecuencia de auroras, situación de la nieve y la realidad de la ventana de reserva para cada mes. Los datos de luz son para Rovaniemi (66,5° N), Saariselkä e Inari son más oscuros en invierno y más claros en verano.',
    th: { month: 'Mes', daylight: 'Luz diurna', aurora: 'Aurora', snow: 'Nieve', vibe: 'Ambiente', booking: 'Reserva', from: 'Desde' },
    secretEyebrow: 'Si puede elegir un solo mes',
    secretH2: 'Marzo es el secreto',
    secretIntro: 'La mayoría de los viajeros de aurora viene en diciembre–enero porque es cuando los días son más oscuros. Pero marzo es el mes en que los repetidores vuelven a reservar. La cuenta:',
    bullets: [
      '11 horas de oscuridad, 13 horas de luz, noche suficiente para ventanas de aurora, día suficiente para esquí + safari sin frontal.',
      'La nieve más fría aún en el suelo, pico de espesor en Levi, Ylläs, Saariselkä. El sol calienta hasta −5 °C, no −30 °C.',
      'Ventanas de aurora aún activas, el óvalo auroral está más activo cerca del equinoccio de primavera. Marzo es estadísticamente uno de los mejores meses de aurora.',
      'Bastante más barato, la mayoría de alojamientos bajan claramente respecto a Navidad/Año Nuevo, y las vacaciones escolares de febrero ya pasaron.',
    ],
    bulletStrong: ['11 horas de oscuridad, 13 horas de luz', 'La nieve más fría aún en el suelo', 'Ventanas de aurora aún activas', 'Bastante más barato'],
    catch: 'El pero: la semana de Pascua (marzo/abril según el año) se agota, el turismo interno finlandés llena las cabañas. Apunte a las tres primeras semanas de marzo si puede.',
    ctaH2: 'Elija el mes, cierre las fechas',
    ctaLead: 'Los iglús de cristal de Kakslauttanen y Levin Iglut se reservan con 8–12 meses de antelación. La Pascua en Lapland Hotels se llena con 6 meses. Cuanto antes decida el mes, más inventario disponible.',
    ctaPrimary: 'Ver precios en Laponia',
    ctaSecondary: 'Ver tipos de alojamiento',
    months: [
      { m: 'Septiembre', daylight: '13 → 11 h', aurora: 'Primeras ventanas · visible en noches despejadas', snow: 'Colores de otoño ruska, aún sin nieve', vibe: 'Mes más tranquilo de la temporada de aurora, adelántese', bookingNote: 'Inventario abierto en todos los alojamientos', fromPrice: '100 €' },
      { m: 'Octubre', daylight: '11 → 8 h', aurora: 'Apariciones frecuentes en noches despejadas', snow: 'Primera nieve a final de mes', vibe: 'Final del ruska, aurora temprana', bookingNote: 'Mejor relación precio-aurora de la temporada', fromPrice: '100 €' },
      { m: 'Noviembre', daylight: '7 → 3 h', aurora: 'Frecuente en noches despejadas · cielos más oscuros', snow: 'Manto de nieve permanente desde mediados', vibe: 'Comienza la noche polar, FIS Levi abre la Copa del Mundo', bookingNote: 'Los iglús de cristal empiezan a llenarse para el siguiente año', fromPrice: '150 €' },
      { m: 'Diciembre', daylight: '2–4 h, "kaamos" noche polar', aurora: 'Frecuente en noches despejadas', snow: 'Nieve de postal', vibe: 'Navidad, Papá Noel, familias', bookingNote: 'La semana de Navidad se reserva 12 meses antes', fromPrice: '250 €' },
      { m: 'Enero', daylight: '4 → 7 h', aurora: 'Frecuente · más frío, más despejado', snow: 'Mayor espesor', vibe: 'Ártico de verdad, mínimas de −30 °C en el interior', bookingNote: 'La semana de Año Nuevo se reserva 10 meses antes', fromPrice: '200 €' },
      { m: 'Febrero', daylight: '7 → 11 h', aurora: 'Frecuente en noches despejadas', snow: 'Espesor pico', vibe: 'Vacaciones escolares, mes más concurrido por familias', bookingNote: 'Semana blanca de mediados de feb se agota 6–8 meses antes', fromPrice: '200 €' },
      { m: 'Marzo', daylight: '11 → 13 h', aurora: 'Aún frecuente · largas tardes de oscuridad', snow: 'Aún profunda, días soleados', vibe: 'El mes secreto, luz, nieve, aurora, menos gente', bookingNote: 'El mejor secreto. Reserve con 4–6 meses', fromPrice: '150 €' },
      { m: 'Abril', daylight: '13 → 17 h', aurora: 'En declive · noches demasiado claras a final de mes', snow: 'Deshielo en Rovaniemi, se aguanta en el norte', vibe: 'Pascua de esquí + aurora, luego deshielo', bookingNote: 'Semana de Pascua agotada, resto del mes flojo', fromPrice: '120 €' },
      { m: 'Mayo', daylight: '17 → 21 h', aurora: 'Prácticamente ninguna', snow: 'Mayormente derretida salvo los fells del norte', vibe: 'Mes de transición, sin nieve, sin sol de medianoche aún', bookingNote: 'Mes más barato para visitar', fromPrice: '80 €' },
      { m: 'Junio', daylight: '24 h sol de medianoche', aurora: 'Imposible (el sol no se pone)', snow: 'Nada al sur de los fells', vibe: 'Sol de medianoche, senderismo, pesca, aún sin insectos', bookingNote: 'Disponibilidad abierta hasta la semana del solsticio', fromPrice: '100 €' },
      { m: 'Julio', daylight: '24 h y luego 22 h', aurora: 'Imposible', snow: 'Ninguna', vibe: 'Pleno verano, mosquitos en el interior, lagos para bañarse', bookingNote: 'Los viajeros nacionales finlandeses llenan las cabañas', fromPrice: '100 €' },
      { m: 'Agosto', daylight: '22 → 16 h', aurora: 'Última semana, vuelven las primeras ventanas', snow: 'Ninguna', vibe: 'Final del verano, ruska empezando a fin de mes', bookingNote: 'Inventario abierto, última calma antes de la temporada de aurora', fromPrice: '100 €' },
    ],
    seasonCards: [
      { title: 'Pico de aurora, nov a mar', body: 'Más oscuro, más frío, más constante. Aurora visible en la mayoría de las noches despejadas. Se agota con 6–12 meses en los iglús de cristal nombrados.' },
      { title: 'Temporada de esquí, dic a abr', body: 'Levi abre con el FIS de slalom en noviembre. Manto fiable dic–mar. La semana de Pascua es la última semana fiable de esquí, abr es deshielo al sur, los fells aguantan al norte.' },
      { title: 'Sol de medianoche, jun a med-jul', body: 'Luz 24 horas al norte del Círculo Polar. Aurora imposible. Inventario tranquilo, precios más bajos, viajeros nacionales finlandeses en cabañas.' },
      { title: 'Ruska, fin de ago a inicio de oct', body: 'Las semanas de color otoñal. Abedules y serbales en rojo y oro. Las primeras ventanas de aurora vuelven a mediados de septiembre. Mejor relación precio-experiencia del año.' },
    ],
  },
}

export default copy
