// Auto-generated by scripts/extract-page-copy.mjs (lang: de)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Wann nach Lappland, Monat für Monat | LaplandStays',
    description: 'Polarlicht-Saison Sep–Apr, Ski-Hochsaison Jan–Mär, Mitternachtssonne Jun–Jul. Monatsweiser Lappland-Leitfaden: wann Unterkünfte ausgebucht sind und Budget.',
  },
  ui: {
    eyebrow: 'Planung',
    h1: 'Beste Reisezeit',

    heroAlt: 'Herbstliche Ruska-Farben auf Lapplands Fjälls, rote und goldene Hänge um einen dunkelblauen See',
    lead: 'Der echte Lappland-Kalender: wann das Polarlicht kommt, wann die Pisten Schnee halten und wann alles ausgebucht ist.',
    seasonsEyebrow: 'Vier sich überlappende Saisons',
    seasonsH2: 'Wählen Sie die Reise, für die Sie kommen',
    monthEyebrow: 'Monat für Monat',
    monthH2: 'Der Lappland-Kalender',
    monthLead: 'Tageslichtstunden, Polarlicht-Frequenz, Schneelage und die Buchungsfenster-Realität für jeden Monat. Tageslichtwerte gelten für Rovaniemi (66,5° N), Saariselkä und Inari sind im Winter dunkler und im Sommer heller.',
    th: { month: 'Monat', daylight: 'Tageslicht', aurora: 'Polarlicht', snow: 'Schnee', vibe: 'Stimmung', booking: 'Buchung', from: 'Ab' },
    secretEyebrow: 'Wenn Sie nur einen Monat wählen können',
    secretH2: 'März ist das Geheimnis',
    secretIntro: 'Die meisten Polarlicht-Reisenden kommen im Dezember/Januar, weil die Tage dann am dunkelsten sind. Aber der März ist der Monat, in dem Reisende, die schon einmal da waren, wieder buchen. Die Rechnung:',
    bullets: [
      '11 Stunden Dunkelheit, 13 Stunden Tageslicht, Nacht lang genug für Polarlicht-Fenster, Tag lang genug für Ski + Safari ohne Stirnlampe.',
      'Kältester Schnee liegt noch, Spitzentiefe in Levi, Ylläs, Saariselkä. Sonne wärmt auf −5 °C, nicht −30 °C.',
      'Polarlicht-Fenster noch aktiv, das Polarlichtoval ist um die Frühlings-Tagundnachtgleiche am aktivsten. Der März ist statistisch einer der besten Polarlicht-Monate.',
      'Deutlich günstiger, die meisten Unterkünfte liegen klar unter den Preisen von Weihnachten/Neujahr, die Schulferien im Februar sind bereits vorbei.',
    ],
    bulletStrong: ['11 Stunden Dunkelheit, 13 Stunden Tageslicht', 'Kältester Schnee liegt noch', 'Polarlicht-Fenster noch aktiv', 'Deutlich günstiger'],
    catch: 'Der Haken: Die Osterwoche (März/April je nach Jahr) ist ausgebucht, finnische Inlandsreisende füllen die Hütten. Zielen Sie auf die ersten drei Märzwochen, wenn möglich.',
    ctaH2: 'Wählen Sie den Monat, sichern Sie die Daten',
    ctaLead: 'Glasiglus in Kakslauttanen und Levin Iglut werden 8–12 Monate im Voraus gebucht. Die Osterwoche in Lapland Hotels füllt sich 6 Monate im Voraus. Je früher Sie sich für einen Monat entscheiden, desto größer das Angebot.',
    ctaPrimary: 'Preise in Lappland ansehen',
    ctaSecondary: 'Unterkunftsarten durchsuchen',
    months: [
      { m: 'September', daylight: '13 → 11 h', aurora: 'Erste Fenster · in klaren Nächten sichtbar', snow: 'Ruska-Herbstfarben, noch kein Schnee', vibe: 'Ruhigster Polarlicht-Monat, vor dem Ansturm', bookingNote: 'Offenes Kontingent in allen Unterkünften' },
      { m: 'Oktober', daylight: '11 → 8 h', aurora: 'Häufige Erscheinungen in klaren Nächten', snow: 'Erster Schnee Ende des Monats', vibe: 'Spätruska, frühes Polarlicht', bookingNote: 'Bestes Preis-Polarlicht-Verhältnis der Saison' },
      { m: 'November', daylight: '7 → 3 h', aurora: 'Häufig in klaren Nächten · dunkelster Himmel', snow: 'Dauerschneedecke ab Monatsmitte', vibe: 'Die dunkelsten Wochen beginnen, FIS Levi eröffnet den Weltcup', bookingNote: 'Glasiglus beginnen sich für die Hauptsaison im Folgejahr zu füllen' },
      { m: 'Dezember', daylight: '2–4 h, lange blaue Dämmerung', aurora: 'Häufig in klaren Nächten', snow: 'Weihnachtskarten-Schnee', vibe: 'Weihnachtssaison, Weihnachtsmann, Familien', bookingNote: 'Weihnachtswoche 12 Monate im Voraus ausgebucht' },
      { m: 'Januar', daylight: '4 → 7 h', aurora: 'Häufig sichtbar · kältester, klarster Himmel', snow: 'Tiefster Schnee', vibe: 'Echte Arktis, Tiefstwerte von −30 °C im Inland', bookingNote: 'Neujahrswoche 10 Monate im Voraus ausgebucht' },
      { m: 'Februar', daylight: '7 → 11 h', aurora: 'Häufig in klaren Nächten', snow: 'Spitzentiefe', vibe: 'Schulferien, geschäftigster Monat mit Familien', bookingNote: 'Mitte-Februar-Halbferien 6–8 Monate im Voraus ausverkauft' },
      { m: 'März', daylight: '11 → 13 h', aurora: 'Weiterhin häufig · lange dunkle Abende', snow: 'Noch tief, sonnige Tage', vibe: 'Der heimliche Monat, Licht, Schnee, Polarlicht, weniger Menschen', bookingNote: 'Bestgehütetes Geheimnis. 4–6 Monate im Voraus' },
      { m: 'April', daylight: '13 → 17 h', aurora: 'Abklingend · Nächte werden Ende des Monats zu hell', snow: 'Tau in Rovaniemi, hält im Norden', vibe: 'Oster-Ski + Polarlicht, dann Tauphase', bookingNote: 'Osterwoche ausgebucht, Rest des Monats ruhig' },
      { m: 'Mai', daylight: '17 → 21 h', aurora: 'Praktisch keines', snow: 'Meist weg außer auf den nördlichen Fjälls', vibe: 'Übergangsmonat, kein Schnee, noch keine Mitternachtssonne', bookingNote: 'Günstigster Monat zum Besuch' },
      { m: 'Juni', daylight: '24 h Mitternachtssonne', aurora: 'Unmöglich (Sonne geht nicht unter)', snow: 'Keiner südlich der Fjälls', vibe: 'Mitternachtssonne, Wandern, Angeln, noch keine Insekten', bookingNote: 'Offene Verfügbarkeit bis zur Mittsommerwoche' },
      { m: 'Juli', daylight: '24 h dann 22 h', aurora: 'Unmöglich', snow: 'Keiner', vibe: 'Hochsommer, Mücken im Inland, Strandseen', bookingNote: 'Finnische Inlandsreisende füllen die Hütten' },
      { m: 'August', daylight: '22 → 16 h', aurora: 'Letzte Woche, erste Fenster kehren zurück', snow: 'Keiner', vibe: 'Spätsommer, Ruska beginnt Ende des Monats', bookingNote: 'Offenes Kontingent, letzte Ruhe vor der Polarlicht-Saison' },
    ],
    seasonCards: [
      { title: 'Polarlicht-Spitze, November bis März', body: 'Dunkelster, kältester, beständigster Zeitraum. Polarlicht in den meisten klaren Nächten sichtbar. 6–12 Monate im Voraus bei benannten Glasiglu-Unterkünften ausgebucht.' },
      { title: 'Ski-Saison, Dezember bis April', body: 'Levi eröffnet mit dem FIS-Slalom im November. Verlässliche Decke Dezember–März. Osterwoche ist die letzte verlässliche Ski-Woche, April Tauphase im Süden, Fjälls im Norden halten.' },
      { title: 'Mitternachtssonne, Juni bis Mitte Juli', body: '24-Stunden-Tageslicht nördlich des Polarkreises. Polarlicht unmöglich. Ruhiges Kontingent, niedrigere Preise, finnische Inlandsreisende in den Hütten.' },
      { title: 'Ruska, Ende August bis Anfang Oktober', body: 'Die Herbstfarbenwochen. Birken und Ebereschen in Rot und Gold. Erste Polarlicht-Fenster kehren Mitte September zurück. Bestes Preis-Erlebnis-Verhältnis des Jahres.' },
    ],
  },
}

export default copy
