// Auto-generated by scripts/extract-page-copy.mjs (lang: zh-CN)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: '何时去拉普兰。逐月指南 | LaplandStays',
    description: '极光季9–4月,滑雪旺季1–3月,午夜阳光6–7月。芬兰拉普兰逐月指南。住宿何时订满、日照时间、可期景象与预算。',
  },
  ui: {
    eyebrow: '规划',
    h1: '何时出行',
    lead: '真实的拉普兰日历。极光窗口何时打开、雪道何时保住雪量、住宿何时提前12个月被订满,以及多数旅行者错过的隐藏便宜月份。',
    seasonsEyebrow: '四个相互交叠的季节',
    seasonsH2: '挑选您来此的旅程',
    monthEyebrow: '逐月解析',
    monthH2: '拉普兰日历',
    monthLead: '每月日照时长、极光出现频率、雪情和预订窗口实情。日照数据以罗瓦涅米(北纬66.5°)为准。萨利色尔卡与伊纳里冬季更黑暗、夏季更明亮。',
    th: { month: '月份', daylight: '日照', aurora: '极光', snow: '雪情', vibe: '氛围', booking: '预订', from: '起价' },
    secretEyebrow: '若只能挑一个月',
    secretH2: '三月才是秘密',
    secretIntro: '大多数极光旅客在12月到1月前来,因为那时夜晚最黑。但回头客的再次预订更多集中在3月。原因如下:',
    bullets: [
      '11小时黑暗、13小时日照。夜够长可观极光,白天够长可滑雪+旅行,无需头灯。',
      '最冷的雪仍在地面。莱维、于拉斯、萨利色尔卡的积雪深度达到峰值。阳光把气温升到−5°C,而非−30°C。',
      '极光窗口依然活跃。极光卵环在春分前后最为活跃。统计上,3月是出现频率最高的月份之一。',
      '价格便宜得多。多数住宿远低于圣诞/新年价格,2月学校假期也已结束。',
    ],
    bulletStrong: ['11小时黑暗、13小时日照', '最冷的雪仍在地面', '极光窗口依然活跃', '价格便宜得多'],
    catch: '陷阱:复活节周(3月或4月,视年份而定)会被订满。芬兰国内旅游会把木屋填满。如果可以,瞄准3月的前三周。',
    ctaH2: '选定月份,锁定日期',
    ctaLead: '卡克斯劳塔宁和莱维Iglut的玻璃穹顶屋需提前8–12个月预订。拉普兰酒店的复活节周提前6个月即被订满。月份决定得越早,选择越多。',
    ctaPrimary: '查看拉普兰价格',
    ctaSecondary: '浏览住宿类型',
    months: [
      { m: '9月', daylight: '13 → 11小时', aurora: '初次窗口 · 晴朗夜晚可见', snow: 'Ruska秋色,尚无雪', vibe: '极光季最静谧的月份。避开人潮', bookingNote: '所有住宿空房充足', fromPrice: '100欧元' },
      { m: '10月', daylight: '11 → 8小时', aurora: '晴夜常有极光', snow: '月末初雪', vibe: '晚秋Ruska,极光提前', bookingNote: '本季最佳性价比', fromPrice: '100欧元' },
      { m: '11月', daylight: '7 → 3小时', aurora: '晴夜常有极光 · 天最黑', snow: '月中开始持久积雪', vibe: '极夜开始,FIS莱维开启世界杯', bookingNote: '玻璃穹顶屋开始为来年高峰订满', fromPrice: '150欧元' },
      { m: '12月', daylight: '2–4小时,"kaamos"极夜', aurora: '晴夜常有极光', snow: '圣诞卡式雪景', vibe: '圣诞季。圣诞老人、家庭旅客', bookingNote: '圣诞周提前12个月预订', fromPrice: '250欧元' },
      { m: '1月', daylight: '4 → 7小时', aurora: '常有极光 · 最冷最清晰', snow: '积雪最深', vibe: '真正北极。内陆低至−30°C', bookingNote: '新年周提前10个月预订', fromPrice: '200欧元' },
      { m: '2月', daylight: '7 → 11小时', aurora: '晴夜常有极光', snow: '积雪峰值', vibe: '学校假期。家庭出游最忙的月份', bookingNote: '2月中假期提前6–8个月售罄', fromPrice: '200欧元' },
      { m: '3月', daylight: '11 → 13小时', aurora: '依然活跃 · 漫长黑夜', snow: '依然深厚,白天阳光明媚', vibe: '秘密之月。光、雪、极光、人少', bookingNote: '最大的秘密。提前4–6个月预订', fromPrice: '150欧元' },
      { m: '4月', daylight: '13 → 17小时', aurora: '逐渐减弱 · 月末夜晚太亮', snow: '罗瓦涅米融化,北部仍有', vibe: '复活节滑雪+极光,随后融雪', bookingNote: '复活节周售罄。月余时间较松', fromPrice: '120欧元' },
      { m: '5月', daylight: '17 → 21小时', aurora: '基本没有', snow: '除北部山区外几乎融化', vibe: '过渡月。既无雪也无午夜阳光', bookingNote: '一年中最便宜的月份', fromPrice: '80欧元' },
      { m: '6月', daylight: '24小时午夜阳光', aurora: '不可能(太阳不落)', snow: '山区以南无雪', vibe: '午夜阳光、徒步、垂钓,蚊虫尚少', bookingNote: '夏至周前空房充足', fromPrice: '100欧元' },
      { m: '7月', daylight: '24小时之后22小时', aurora: '不可能', snow: '无', vibe: '盛夏。内陆有蚊,沙滩湖泊', bookingNote: '芬兰国内旅客填满小屋', fromPrice: '100欧元' },
      { m: '8月', daylight: '22 → 16小时', aurora: '最后一周。首批窗口回归', snow: '无', vibe: '夏末,月底开始Ruska', bookingNote: '空房充足,是极光季前最后的安静', fromPrice: '100欧元' },
    ],
    seasonCards: [
      { title: '极光高峰。11月至3月', body: '最黑暗、最寒冷、最稳定。多数晴朗夜晚可见极光。在知名玻璃穹顶屋,提前6–12个月即被订满。' },
      { title: '滑雪季。12月至4月', body: '莱维在11月以FIS回转赛开赛。12月至3月雪情可靠。复活节周是最后一周可靠滑雪周。4月南部融化,北部山区仍可滑。' },
      { title: '午夜阳光。6月至7月中旬', body: '北极圈以北24小时日照。极光不可能。空房充足、价格更低,芬兰国内旅客住进小屋。' },
      { title: 'Ruska。8月末至10月初', body: '秋色周。桦树与花楸披上红金。最早的极光窗口在9月中旬回归。一年中性价比最高。' },
    ],
  },
}

export default copy
