// Auto-generated by scripts/extract-page-copy.mjs (lang: pt-BR)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: 'Quando ir à Lapônia, mês a mês | LaplandStays',
    description: 'Aurora set–abr, esqui jan–mar, sol da meia-noite jun–jul. Guia mês a mês da Lapônia: quando as hospedagens esgotam, horas de luz e orçamento.',
  },
  ui: {
    eyebrow: 'Planejamento',
    h1: 'Quando ir',
    heroAlt: 'Cores da ruska de outono nos fells da Lapônia, encostas vermelhas e douradas ao redor de um lago azul-escuro',
    lead: 'O calendário real da Lapônia: quando a aurora aparece, quando as pistas seguram a neve e quando tudo esgota.',
    seasonsEyebrow: 'Quatro temporadas sobrepostas',
    seasonsH2: 'Escolha a viagem pela qual veio',
    monthEyebrow: 'Mês a mês',
    monthH2: 'O calendário da Lapônia',
    monthLead: 'Horas de luz, frequência de aurora, situação da neve e a realidade da janela de reserva pra cada mês. Os dados de luz são de Rovaniemi (66,5° N), Saariselkä e Inari são mais escuros no inverno e mais claros no verão.',
    th: { month: 'Mês', daylight: 'Luz', aurora: 'Aurora', snow: 'Neve', vibe: 'Clima', booking: 'Reserva', from: 'A partir de' },
    secretEyebrow: 'Se puder escolher um mês só',
    secretH2: 'Março é o segredo',
    secretIntro: 'A maioria dos viajantes de aurora vem em dezembro–janeiro porque é quando os dias são mais escuros. Mas março é o mês em que os repetidores reservam de novo. A conta:',
    bullets: [
      '11 horas de escuridão, 13 horas de luz, noite longa o bastante pras janelas de aurora, dia longo o bastante pra esqui + safári sem lanterna de cabeça.',
      'A neve mais fria ainda no chão, pico de profundidade em Levi, Ylläs, Saariselkä. O sol esquenta até −5 °C, não −30 °C.',
      'Janelas de aurora ainda ativas, o oval auroral está mais ativo perto do equinócio de primavera. Março é estatisticamente um dos melhores meses de frequência de aurora.',
      'Bem mais barato, a maioria das hospedagens cai bastante em relação ao Natal/Ano Novo, e o recesso escolar de fevereiro já passou.',
    ],
    bulletStrong: ['11 horas de escuridão, 13 horas de luz', 'A neve mais fria ainda no chão', 'Janelas de aurora ainda ativas', 'Bem mais barato'],
    catch: 'O porém: a semana de Páscoa (março/abril dependendo do ano) esgota, o turismo doméstico finlandês lota as cabanas. Mire nas três primeiras semanas de março se conseguir.',
    ctaH2: 'Escolha o mês, trave as datas',
    ctaLead: 'Os iglus de vidro de Kakslauttanen e Levin Iglut são reservados com 8–12 meses. A Páscoa em Lapland Hotels lota com 6 meses. Quanto antes você decidir o mês, mais ampla a oferta.',
    ctaPrimary: 'Ver preços na Lapônia',
    ctaSecondary: 'Ver tipos de hospedagem',
    months: [
      { m: 'Setembro', daylight: '13 → 11 h', aurora: 'Primeiras janelas · visível em noites limpas', snow: 'Cores de outono ruska, ainda sem neve', vibe: 'Mês mais quieto da temporada de aurora, fuja do pico', bookingNote: 'Disponibilidade aberta em todas as hospedagens' },
      { m: 'Outubro', daylight: '11 → 8 h', aurora: 'Aparições frequentes em noites limpas', snow: 'Primeira neve no fim do mês', vibe: 'Final do ruska, aurora cedo', bookingNote: 'Melhor relação custo-aurora da temporada' },
      { m: 'Novembro', daylight: '7 → 3 h', aurora: 'Frequente em noites limpas · céu mais escuro', snow: 'Cobertura permanente a partir da metade do mês', vibe: 'Começa a noite polar, FIS Levi abre a Copa do Mundo', bookingNote: 'Iglus de vidro começam a lotar para o pico do ano seguinte' },
      { m: 'Dezembro', daylight: '2–4 h, "kaamos" noite polar', aurora: 'Frequente em noites limpas', snow: 'Neve de cartão postal', vibe: 'Temporada de Natal, Papai Noel, famílias', bookingNote: 'Semana do Natal é reservada com 12 meses' },
      { m: 'Janeiro', daylight: '4 → 7 h', aurora: 'Frequente · mais frio e mais limpo', snow: 'Maior profundidade', vibe: 'Ártico de verdade, mínimas de −30 °C no interior', bookingNote: 'Semana de Ano Novo é reservada com 10 meses' },
      { m: 'Fevereiro', daylight: '7 → 11 h', aurora: 'Frequente em noites limpas', snow: 'Pico de profundidade', vibe: 'Recesso escolar, mês mais cheio com famílias', bookingNote: 'Semana de carnaval finlandês esgota com 6–8 meses' },
      { m: 'Março', daylight: '11 → 13 h', aurora: 'Ainda frequente · longas noites escuras', snow: 'Ainda profunda, dias ensolarados', vibe: 'O mês secreto, luz, neve, aurora, menos gente', bookingNote: 'O segredo melhor guardado. Reserve com 4–6 meses' },
      { m: 'Abril', daylight: '13 → 17 h', aurora: 'Em declínio · noites claras demais no fim do mês', snow: 'Derretendo em Rovaniemi, aguenta no norte', vibe: 'Esqui de Páscoa + aurora, depois derretimento', bookingNote: 'Semana de Páscoa esgota, resto do mês mais leve' },
      { m: 'Maio', daylight: '17 → 21 h', aurora: 'Praticamente nenhuma', snow: 'Quase toda derretida exceto fells do norte', vibe: 'Mês de transição, sem neve, sem sol da meia-noite ainda', bookingNote: 'Mês mais barato pra visitar' },
      { m: 'Junho', daylight: '24 h sol da meia-noite', aurora: 'Impossível (o sol não se põe)', snow: 'Nenhuma ao sul dos fells', vibe: 'Sol da meia-noite, trilhas, pesca, ainda sem insetos', bookingNote: 'Disponibilidade aberta até a semana do solstício' },
      { m: 'Julho', daylight: '24 h e depois 22 h', aurora: 'Impossível', snow: 'Nenhuma', vibe: 'Pico do verão, mosquitos no interior, lagos pra banho', bookingNote: 'Viajantes domésticos finlandeses lotam as cabanas' },
      { m: 'Agosto', daylight: '22 → 16 h', aurora: 'Última semana, primeiras janelas voltam', snow: 'Nenhuma', vibe: 'Final do verão, ruska começando no fim do mês', bookingNote: 'Disponibilidade aberta, última calma antes da temporada de aurora' },
    ],
    seasonCards: [
      { title: 'Pico de aurora, nov a mar', body: 'Mais escuro, mais frio, mais consistente. Aurora visível na maioria das noites limpas. Esgota com 6–12 meses em iglus de vidro famosos.' },
      { title: 'Temporada de esqui, dez a abr', body: 'Levi abre com o FIS slalom em novembro. Cobertura confiável dez–mar. Semana de Páscoa é a última semana confiável de esqui, abr é derretimento ao sul, fells ao norte aguentam.' },
      { title: 'Sol da meia-noite, jun a meados de jul', body: 'Luz 24 horas ao norte do Círculo Polar. Aurora impossível. Disponibilidade tranquila, preços mais baixos, viajantes domésticos finlandeses nas cabanas.' },
      { title: 'Ruska, fim de ago a início de out', body: 'As semanas de cor de outono. Bétulas e sorveiras em vermelho e dourado. Primeiras janelas de aurora voltam em meados de setembro. Melhor relação preço-experiência do ano.' },
    ],
  },
}

export default copy
