// Auto-generated by scripts/extract-page-copy.mjs (lang: zh-CN)
import type { PageCopy } from './WhenToGo.copy.types'

const copy: PageCopy = {
  seo: {
    title: '何時去拉普蘭。逐月指南',
    description: '極光季9–4月，滑雪旺季1–3月，午夜陽光6–7月。芬蘭拉普蘭逐月指南。住宿何時訂滿、日照時間、可期景象與預算。',
  },
  ui: {
    eyebrow: '規劃',
    h1: '何時出行',
    heroAlt: '拉普蘭山地的ruska秋色，深藍湖泊周圍紅金色的山坡',
    lead: '真實的拉普蘭日曆：極光何時出現、雪道何時有雪，以及一切何時被訂滿。',
    seasonsEyebrow: '四個相互交疊的季節',
    seasonsH2: '挑選您來此的旅程',
    monthEyebrow: '逐月解析',
    monthH2: '拉普蘭日曆',
    monthLead: '每月日照時長、極光出現頻率、雪情和預訂視窗實情。日照資料以羅瓦涅米（北緯66.5°）為準。薩利色爾卡與伊納里冬季更黑暗、夏季更明亮。',
    th: { month: '月份', daylight: '日照', aurora: '極光', snow: '雪情', vibe: '氛圍', booking: '預訂', from: '起價' },
    secretEyebrow: '若只能挑一個月',
    secretH2: '三月才是秘密',
    secretIntro: '大多數極光旅客在12月到1月前來，因為那時夜晚最黑。但回頭客的再次預訂更多集中在3月。原因如下：',
    bullets: [
      '11小時黑暗、13小時日照。夜夠長可觀極光，白天夠長可滑雪+旅行，無需頭燈。',
      '最冷的雪仍在地面。萊維、於拉斯、薩利色爾卡的積雪深度達到峰值。陽光把氣溫升到−5°C，而非−30°C。',
      '極光視窗依然活躍。極光橢圓帶在春分前後最為活躍。統計上，3月是出現頻率最高的月份之一。',
      '價格便宜得多。多數住宿遠低於聖誕/新年價格，2月學校假期也已結束。',
    ],
    bulletStrong: ['11小時黑暗、13小時日照', '最冷的雪仍在地面', '極光視窗依然活躍', '價格便宜得多'],
    catch: '陷阱：復活節周（3月或4月，視年份而定）會被訂滿。芬蘭國內旅遊會把木屋填滿。如果可以，瞄準3月的前三週。',
    ctaH2: '選定月份，鎖定日期',
    ctaLead: '卡克斯勞塔寧和萊維Iglut的玻璃屋需提前8–12個月預訂。拉普蘭飯店的復活節周提前6個月即被訂滿。月份決定得越早，選擇越多。',
    ctaPrimary: '檢視拉普蘭價格',
    ctaSecondary: '瀏覽住宿類型',
    months: [
      { m: '9月', daylight: '13 → 11小時', aurora: '初次視窗 · 晴朗夜晚可見', snow: 'Ruska秋色，尚無雪', vibe: '極光季最靜謐的月份。避開人潮', bookingNote: '所有住宿空房充足' },
      { m: '10月', daylight: '11 → 8小時', aurora: '晴夜常有極光', snow: '月末初雪', vibe: '晚秋Ruska，極光提前', bookingNote: '本季最佳CP值' },
      { m: '11月', daylight: '7 → 3小時', aurora: '晴夜常有極光 · 天最黑', snow: '月中開始持久積雪', vibe: '最暗的時節開始，FIS萊維開啟世界盃', bookingNote: '玻璃屋開始為來年高峰訂滿' },
      { m: '12月', daylight: '2–4小時，漫長的藍色暮光', aurora: '晴夜常有極光', snow: '聖誕卡式雪景', vibe: '聖誕季。聖誕老人、家庭旅客', bookingNote: '聖誕周提前12個月預訂' },
      { m: '1月', daylight: '4 → 7小時', aurora: '常有極光 · 最冷最清晰', snow: '積雪最深', vibe: '真正北極。內陸低至−30°C', bookingNote: '新年周提前10個月預訂' },
      { m: '2月', daylight: '7 → 11小時', aurora: '晴夜常有極光', snow: '積雪峰值', vibe: '學校假期。家庭出遊最忙的月份', bookingNote: '2月中假期提前6–8個月售罄' },
      { m: '3月', daylight: '11 → 13小時', aurora: '依然活躍 · 漫長黑夜', snow: '依然深厚，白天陽光明媚', vibe: '秘密之月。光、雪、極光、人少', bookingNote: '最大的秘密。提前4–6個月預訂' },
      { m: '4月', daylight: '13 → 17小時', aurora: '逐漸減弱 · 月末夜晚太亮', snow: '羅瓦涅米融化，北部仍有', vibe: '復活節滑雪+極光，隨後融雪', bookingNote: '復活節周售罄。月餘時間較松' },
      { m: '5月', daylight: '17 → 21小時', aurora: '基本沒有', snow: '除北部山區外幾乎融化', vibe: '過渡月。既無雪也無午夜陽光', bookingNote: '一年中最便宜的月份' },
      { m: '6月', daylight: '24小時午夜陽光', aurora: '不可能（太陽不落）', snow: '山區以南無雪', vibe: '午夜陽光、徒步、垂釣，蚊蟲尚少', bookingNote: '夏至周前空房充足' },
      { m: '7月', daylight: '24小時之後22小時', aurora: '不可能', snow: '無', vibe: '盛夏。內陸有蚊，沙灘湖泊', bookingNote: '芬蘭國內旅客填滿小屋' },
      { m: '8月', daylight: '22 → 16小時', aurora: '最後一週。首批視窗迴歸', snow: '無', vibe: '夏末，月底開始Ruska', bookingNote: '空房充足，是極光季前最後的安靜' },
    ],
    seasonCards: [
      { title: '極光高峰。11月至3月', body: '最黑暗、最寒冷、最穩定。多數晴朗夜晚可見極光。在知名玻璃屋，提前6–12個月即被訂滿。' },
      { title: '滑雪季。12月至4月', body: '萊維在11月以FIS迴轉賽開賽。12月至3月雪情可靠。復活節周是最後一週可靠滑雪周。4月南部融化，北部山區仍可滑。' },
      { title: '午夜陽光。6月至7月中旬', body: '北極圈以北24小時日照。極光不可能。空房充足、價格更低，芬蘭國內旅客住進小屋。' },
      { title: 'Ruska。8月末至10月初', body: '秋色周。樺樹與花楸披上紅金。最早的極光視窗在9月中旬迴歸。一年中CP值最高。' },
    ],
  },
}

export default copy
