import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'ホーム',
    breadcrumbDest: '目的地',
    overviewEyebrow: '概要',
    overviewH2: (n: string) => `${n}に滞在する理由`,
    seePricesIn: (n: string) => `${n}の料金を見る`,
    highlightsEyebrow: '特別な理由',
    highlightsH2: (n: string) => `${n}のハイライト`,
    whenToGoEyebrow: '訪れる時期',
    seasonsH3: '季節',
    gettingThereEyebrow: 'アクセス',
    travelH3: '移動手段',
    staysInEyebrow: (n: string) => `${n}での宿泊`,
    whatToBookH2: '予約する内容',
    findCabinH3: (n: string) => `${n}のロッジを探す`,
    findCabinLead: '空室と料金を比較。仲介手数料はかかりません。',
    checkAvailability: '空室を確認',
    anchorEyebrow: '主要施設',
    whereToStayH2: (n: string) => `${n}でどこに泊まるか`,
    anchorLead: 'Trip.comの最新料金へ。ピーク期は4〜8カ月前の予約が必要です。',
    gettingThereH2: (n: string) => `${n}までの交通`,
    transportLead: '運営者ページの実料金。季節ごとに再確認。送迎は通常、宿泊施設経由で事前予約が可能です。',
    rentCarLabel: 'レンタカー · EconomyBookings',
    sampleItinerary: 'モデル日程',
    dayPlanH2: (n: number, name: string) => `${name}の${n}日間プラン`,
    dayPlanLead: '典型的なオーロラシーズンの旅の流れです。ご経験に合わせて調整してください。これは出発点であって、決まりではありません。',
    moreLapland: 'もっとラップランド',
    otherDestinations: '他の目的地',
    seeStays: '宿泊先を見る',
    finnishLapland: 'フィンランド・ラップランド',
    readMore: "ラップランドで見る",
    planTripEyebrow: "滞在の先へ",
    planTripH2: "旅全体をプランニング",
    planActivities: "アクティビティ",
    planSkiResorts: "スキーリゾート",
    planTransfers: "送迎・交通",
    planCarRental: "レンタカー",
  }

export default copy