import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: '홈',
    breadcrumbDest: '목적지',
    overviewEyebrow: '개요',
    overviewH2: (n: string) => `${n}에 머무는 이유`,
    seePricesIn: (n: string) => `${n} 요금 보기`,
    highlightsEyebrow: '특별한 이유',
    highlightsH2: (n: string) => `${n}의 하이라이트`,
    whenToGoEyebrow: '방문 시기',
    seasonsH3: '계절',
    gettingThereEyebrow: '가는 방법',
    travelH3: '교통',
    staysInEyebrow: (n: string) => `${n} 숙박`,
    whatToBookH2: '무엇을 예약할까',
    findCabinH3: (n: string) => `${n}의 캐빈을 찾으세요`,
    findCabinLead: '객실과 요금을 한 번에 비교하세요. 중개 수수료는 없습니다.',
    checkAvailability: '객실 확인',
    anchorEyebrow: '대표 숙소',
    whereToStayH2: (n: string) => `${n}에서 어디에 묵을까`,
    anchorLead: '실시간 Trip.com 요금으로 바로 이동합니다. 성수기에는 4–8개월 전 예약이 필요합니다.',
    gettingThereH2: (n: string) => `${n}까지 가는 길`,
    transportLead: '운영사 페이지에서 확인한 실제 운임. 시즌마다 재검토합니다. 픽업은 보통 숙소를 통해 사전 예약하실 수 있습니다.',
    rentCarLabel: '렌터카 · EconomyBookings',
    sampleItinerary: '추천 일정',
    dayPlanH2: (n: number, name: string) => `${name} ${n}일 코스`,
    dayPlanLead: '오로라 시즌의 전형적인 여행 흐름입니다. 본인의 페이스에 맞춰 조정해 보세요. 정답이 아닌 출발점일 뿐입니다.',
    moreLapland: '라플란드 더 보기',
    otherDestinations: '다른 목적지',
    seeStays: '숙소 보기',
    finnishLapland: '핀란드 라플란드',
    readMore: "라플란드에서 둘러보기",
    planTripEyebrow: "숙박 그 너머",
    planTripH2: "여행 전체 계획하기",
    planActivities: "액티비티",
    planTransfers: "교통·픽업",
    planCarRental: "렌터카",
  }

export default copy