import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: '首頁',
    overviewEyebrow: '概覽',
    overviewH2: (n: string) => `為何選擇在${n}住宿`,
    seePricesIn: (n: string) => `檢視${n}的價格`,
    highlightsEyebrow: '它的獨特之處',
    highlightsH2: (n: string) => `${n}的亮點`,
    whenToGoEyebrow: '何時出行',
    seasonsH3: '季節',
    gettingThereEyebrow: '前往方式',
    travelH3: '出行',
    staysInEyebrow: (n: string) => `${n}住宿`,
    whatToBookH2: '該預訂什麼',
    findCabinH3: (n: string) => `在${n}找到您的小屋`,
    findCabinLead: '檢視空房並比較價格。沒有中介費。',
    checkAvailability: '檢視空房',
    anchorEyebrow: '主要住宿',
    whereToStayH2: (n: string) => `${n}在哪裡住`,
    anchorLead: '點選檢視Trip.com即時價格。旺季需提前4–8個月預訂。',
    gettingThereH2: (n: string) => `前往${n}的交通`,
    transportLead: '來自運營商頁面的真實價格。每季度複核。接送通常可通過住宿提前預訂。',
    rentCarLabel: '租車 · EconomyBookings',
    sampleItinerary: '樣本行程',
    dayPlanH2: (n: number, name: string) => `${name}的${n}日方案`,
    dayPlanLead: '典型極光季旅程的輪廓。可按水平自行調整。這些是起點，不是處方。',
    moreLapland: '更多拉普蘭',
    otherDestinations: '其他目的地',
    seeStays: '檢視住宿',
    finnishLapland: '芬蘭拉普蘭',
    readMore: "在拉普蘭探索",
    planTripEyebrow: "住宿之外",
    planTripH2: "規劃整趟旅程",
    planActivities: "活動",
    planSkiResorts: "滑雪度假區",
    planTransfers: "接駁交通",
    planCarRental: "租車",
  }

export default copy