import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: '首页',
    breadcrumbDest: '目的地',
    overviewEyebrow: '概览',
    overviewH2: (n: string) => `为何选择在${n}住宿`,
    seePricesIn: (n: string) => `查看${n}的价格`,
    highlightsEyebrow: '它的独特之处',
    highlightsH2: (n: string) => `${n}的亮点`,
    whenToGoEyebrow: '何时出行',
    seasonsH3: '季节',
    gettingThereEyebrow: '前往方式',
    travelH3: '出行',
    staysInEyebrow: (n: string) => `${n}住宿`,
    whatToBookH2: '该预订什么',
    findCabinH3: (n: string) => `在${n}找到您的小屋`,
    findCabinLead: '查看空房并比较价格。没有中介费。',
    checkAvailability: '查看空房',
    anchorEyebrow: '主要住宿',
    whereToStayH2: (n: string) => `${n}在哪里住`,
    anchorLead: '点击查看Trip.com实时价格。旺季需提前4–8个月预订。',
    gettingThereH2: (n: string) => `前往${n}的交通`,
    transportLead: '来自运营商页面的真实价格。每季度复核。接送通常可通过住宿提前预订。',
    rentCarLabel: '租车 · EconomyBookings',
    sampleItinerary: '样本行程',
    dayPlanH2: (n: number, name: string) => `${name}的${n}日方案`,
    dayPlanLead: '典型极光季旅程的轮廓。可按水平自行调整。这些是起点,不是处方。',
    moreLapland: '更多拉普兰',
    otherDestinations: '其他目的地',
    seeStays: '查看住宿',
    finnishLapland: '芬兰拉普兰',
    readMore: "在拉普兰探索",
    planTripEyebrow: "住宿之外",
    planTripH2: "规划整趟旅程",
    planActivities: "活动",
    planSkiResorts: "滑雪度假区",
    planTransfers: "接驳交通",
    planCarRental: "租车",
  }

export default copy