import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Start',
    breadcrumbDest: 'Reiseziele',
    overviewEyebrow: 'Überblick',
    overviewH2: (n: string) => `Warum in ${n} übernachten`,
    seePricesIn: (n: string) => `Preise in ${n} ansehen`,
    highlightsEyebrow: 'Was es besonders macht',
    highlightsH2: (n: string) => `Highlights von ${n}`,
    whenToGoEyebrow: 'Beste Reisezeit',
    seasonsH3: 'Jahreszeiten',
    gettingThereEyebrow: 'Anreise',
    travelH3: 'Reise',
    staysInEyebrow: (n: string) => `Übernachten in ${n}`,
    whatToBookH2: 'Was buchen',
    findCabinH3: (n: string) => `Ihre Hütte in ${n} finden`,
    findCabinLead: 'Verfügbarkeit prüfen und Preise vergleichen, keine Vermittlungsgebühren.',
    checkAvailability: 'Verfügbarkeit prüfen',
    anchorEyebrow: 'Anker-Unterkünfte',
    whereToStayH2: (n: string) => `Wo in ${n} übernachten`,
    anchorLead: 'Durchklicken zu tagesaktuellen Trip.com-Preisen. Unterkünfte werden in der Hauptsaison 4–8 Monate im Voraus gebucht.',
    gettingThereH2: (n: string) => `Anreise nach ${n}`,
    transportLead: 'Echte Preise von den Betreiberseiten, saisonal überprüft. Transfers meist über Ihre Unterkunft vorbuchbar.',
    rentCarLabel: 'Mietwagen · EconomyBookings',
    sampleItinerary: 'Beispiel-Reiseplan',
    dayPlanH2: (n: number, name: string) => `Ein ${n}-Tages-Plan für ${name}`,
    dayPlanLead: 'Die Struktur einer typischen Polarlicht-Saison-Reise. Passen Sie sie an Ihr Können an, das sind Ausgangspunkte, keine Vorschriften.',
    moreLapland: 'Mehr Lappland',
    otherDestinations: 'Andere Reiseziele',
    seeStays: 'Unterkünfte ansehen',
    finnishLapland: 'Finnisch Lappland',
    readMore: "In Lappland entdecken",
    planTripEyebrow: "Mehr als die Unterkunft",
    planTripH2: "Die ganze Reise planen",
    planActivities: "Aktivitäten",
    planSkiResorts: "Skigebiete",
    planTransfers: "Transfers",
    planCarRental: "Mietwagen",
  }

export default copy