import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Home',
    overviewEyebrow: 'Panoramica',
    overviewH2: (n: string) => `Perché soggiornare a ${n}`,
    seePricesIn: (n: string) => `Vedi i prezzi a ${n}`,
    highlightsEyebrow: 'Cosa la rende speciale',
    highlightsH2: (n: string) => `Punti forti di ${n}`,
    whenToGoEyebrow: 'Quando andare',
    seasonsH3: 'Stagioni',
    gettingThereEyebrow: 'Come arrivare',
    travelH3: 'Viaggio',
    staysInEyebrow: (n: string) => `Soggiorni a ${n}`,
    whatToBookH2: 'Cosa prenotare',
    findCabinH3: (n: string) => `Trova il Suo chalet a ${n}`,
    findCabinLead: 'Verifichi disponibilità e confronti le tariffe, niente commissioni di intermediazione.',
    checkAvailability: 'Verifica disponibilità',
    anchorEyebrow: 'Strutture-ancora',
    whereToStayH2: (n: string) => `Dove soggiornare a ${n}`,
    anchorLead: 'Clicchi per accedere alle tariffe aggiornate su Trip.com. In alta stagione le strutture si prenotano con 4–8 mesi di anticipo.',
    gettingThereH2: (n: string) => `Come raggiungere ${n}`,
    transportLead: 'Tariffe reali dalle pagine degli operatori, verificate ogni stagione. I trasferimenti sono di norma prenotabili in anticipo tramite la struttura.',
    rentCarLabel: 'Noleggia un\'auto · EconomyBookings',
    sampleItinerary: 'Itinerario tipo',
    dayPlanH2: (n: number, name: string) => `Un piano di ${n} giorni a ${name}`,
    dayPlanLead: 'L\'andamento di un tipico viaggio in stagione di aurora. Lo adatti al Suo livello, sono spunti, non prescrizioni.',
    moreLapland: 'Altra Lapponia',
    otherDestinations: 'Altre destinazioni',
    seeStays: 'Vedi i soggiorni',
    finnishLapland: 'Lapponia finlandese',
    readMore: "Scopri in Lapponia",
    planTripEyebrow: "Oltre il soggiorno",
    planTripH2: "Pianifica l'intero viaggio",
    planActivities: "Attività",
    planSkiResorts: "Comprensori sciistici",
    planTransfers: "Trasferimenti",
    planCarRental: "Noleggio auto",
  }

export default copy