import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Início',
    breadcrumbDest: 'Destinos',
    overviewEyebrow: 'Visão geral',
    overviewH2: (n: string) => `Por que se hospedar em ${n}`,
    seePricesIn: (n: string) => `Ver preços em ${n}`,
    highlightsEyebrow: 'O que torna especial',
    highlightsH2: (n: string) => `Destaques de ${n}`,
    whenToGoEyebrow: 'Quando ir',
    seasonsH3: 'Estações',
    gettingThereEyebrow: 'Como chegar',
    travelH3: 'Viagem',
    staysInEyebrow: (n: string) => `Hospedagem em ${n}`,
    whatToBookH2: 'O que reservar',
    findCabinH3: (n: string) => `Encontre sua cabana em ${n}`,
    findCabinLead: 'Confira a disponibilidade e compare tarifas, sem taxas de intermediário.',
    checkAvailability: 'Ver disponibilidade',
    anchorEyebrow: 'Hospedagens-âncora',
    whereToStayH2: (n: string) => `Onde se hospedar em ${n}`,
    anchorLead: 'Clique para ver tarifas verificadas no Hotels.com. As hospedagens são reservadas 4–8 meses antes na alta temporada.',
    gettingThereH2: (n: string) => `Transporte para ${n}`,
    transportLead: 'Tarifas reais das páginas dos operadores, reconferidas sazonalmente. Os transfers geralmente são reservados via sua hospedagem.',
    rentCarLabel: 'Alugar carro · EconomyBookings',
    sampleItinerary: 'Itinerário modelo',
    dayPlanH2: (n: number, name: string) => `Um plano de ${n} dias em ${name}`,
    dayPlanLead: 'A forma de uma viagem típica em temporada de aurora. Ajuste pelo nível, são pontos de partida, não receita.',
    moreLapland: 'Mais Lapônia',
    otherDestinations: 'Outros destinos',
    seeStays: 'Ver hospedagens',
    finnishLapland: 'Lapônia finlandesa',
    readMore: "Descobrir na Lapônia",
    planTripEyebrow: "Além da hospedagem",
    planTripH2: "Planeje a viagem inteira",
    planActivities: "Atividades",
    planTransfers: "Traslados",
    planCarRental: "Aluguel de carro",
  }

export default copy