import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Hem',
    overviewEyebrow: 'Översikt',
    overviewH2: (n: string) => `Varför bo i ${n}`,
    seePricesIn: (n: string) => `Se priser i ${n}`,
    highlightsEyebrow: 'Det som gör det speciellt',
    highlightsH2: (n: string) => `Höjdpunkter i ${n}`,
    whenToGoEyebrow: 'När du ska åka',
    seasonsH3: 'Årstider',
    gettingThereEyebrow: 'Ta dig dit',
    travelH3: 'Resa',
    staysInEyebrow: (n: string) => `Boende i ${n}`,
    whatToBookH2: 'Vad du ska boka',
    findCabinH3: (n: string) => `Hitta din stuga i ${n}`,
    findCabinLead: 'Kontrollera tillgänglighet och jämför priser – inga mellanhandsavgifter.',
    checkAvailability: 'Kontrollera tillgänglighet',
    anchorEyebrow: 'Ankarboenden',
    whereToStayH2: (n: string) => `Var du bor i ${n}`,
    anchorLead: 'Klicka vidare till aktuella priser på Trip.com. Under högsäsong bokas boendena 4–8 månader i förväg.',
    gettingThereH2: (n: string) => `Transport till ${n}`,
    transportLead: 'Verkliga priser från leverantörernas sidor – kontrollerade varje säsong. Transfer går oftast att förboka via ditt boende.',
    rentCarLabel: 'Hyr bil · EconomyBookings',
    sampleItinerary: 'Exempel på resplan',
    dayPlanH2: (n: number, name: string) => `En resplan på ${n} dagar i ${name}`,
    dayPlanLead: 'Så ser en typisk resa under norrskenssäsongen ut. Anpassa efter din nivå – det här är utgångspunkter, inte regler.',
    moreLapland: 'Mer Lappland',
    otherDestinations: 'Andra destinationer',
    seeStays: 'Se boenden',
    finnishLapland: 'Finska Lappland',
    readMore: "Upptäck i Lappland",
    planTripEyebrow: "Mer än övernattningen",
    planTripH2: "Planera hela resan",
    planActivities: "Aktiviteter",
    planSkiResorts: "Skidorter",
    planTransfers: "Transfer",
    planCarRental: "Bilhyra",
  }

export default copy