import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Start',
    breadcrumbDest: 'Bestemmingen',
    overviewEyebrow: 'Overzicht',
    overviewH2: (n: string) => `Waarom verblijven in ${n}`,
    seePricesIn: (n: string) => `Prijzen in ${n} bekijken`,
    highlightsEyebrow: 'Wat het bijzonder maakt',
    highlightsH2: (n: string) => `Hoogtepunten van ${n}`,
    whenToGoEyebrow: 'Wanneer te gaan',
    seasonsH3: 'Seizoenen',
    gettingThereEyebrow: 'Heenreis',
    travelH3: 'Reizen',
    staysInEyebrow: (n: string) => `Verblijven in ${n}`,
    whatToBookH2: 'Wat te boeken',
    findCabinH3: (n: string) => `Vind uw cabin in ${n}`,
    findCabinLead: 'Bekijk beschikbaarheid en vergelijk tarieven, geen tussenhandelkosten.',
    checkAvailability: 'Beschikbaarheid bekijken',
    anchorEyebrow: 'Anker-accommodaties',
    whereToStayH2: (n: string) => `Waar verblijven in ${n}`,
    anchorLead: 'Klik door naar actuele tarieven op Trip.com. In het hoogseizoen wordt 4–8 maanden vooruit geboekt.',
    gettingThereH2: (n: string) => `Vervoer naar ${n}`,
    transportLead: 'Reële prijzen van aanbiederpagina\'s, per seizoen opnieuw nagekeken. Transfers zijn meestal vooruit te boeken via uw accommodatie.',
    rentCarLabel: 'Auto huren · EconomyBookings',
    sampleItinerary: 'Voorbeeldroute',
    dayPlanH2: (n: number, name: string) => `Een plan van ${n} dagen in ${name}`,
    dayPlanLead: 'De opbouw van een typische reis in het aurora-seizoen. Pas aan op uw niveau, dit zijn startpunten, geen voorschriften.',
    moreLapland: 'Meer Lapland',
    otherDestinations: 'Andere bestemmingen',
    seeStays: 'Verblijven bekijken',
    finnishLapland: 'Fins Lapland',
    readMore: "Ontdek in Lapland",
    planTripEyebrow: "Meer dan de overnachting",
    planTripH2: "Plan de hele reis",
    planActivities: "Activiteiten",
    planTransfers: "Vervoer",
    planCarRental: "Autohuur",
  }

export default copy