import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Accueil',
    breadcrumbDest: 'Destinations',
    overviewEyebrow: 'Aperçu',
    overviewH2: (n: string) => `Pourquoi séjourner à ${n}`,
    seePricesIn: (n: string) => `Voir les prix à ${n}`,
    highlightsEyebrow: 'Ce qui fait sa singularité',
    highlightsH2: (n: string) => `Les temps forts de ${n}`,
    whenToGoEyebrow: 'Quand y aller',
    seasonsH3: 'Saisons',
    gettingThereEyebrow: 'Y aller',
    travelH3: 'Trajet',
    staysInEyebrow: (n: string) => `Séjours à ${n}`,
    whatToBookH2: 'Que réserver',
    findCabinH3: (n: string) => `Trouvez votre chalet à ${n}`,
    findCabinLead: 'Vérifiez la disponibilité et comparez les tarifs, sans frais d\'intermédiaire.',
    checkAvailability: 'Vérifier la disponibilité',
    anchorEyebrow: 'Hébergements piliers',
    whereToStayH2: (n: string) => `Où loger à ${n}`,
    anchorLead: 'Cliquez pour des tarifs vérifiés sur Hotels.com. Les hébergements se réservent 4 à 8 mois à l\'avance en haute saison.',
    gettingThereH2: (n: string) => `Transports vers ${n}`,
    transportLead: 'Tarifs réels relevés sur les pages des opérateurs, révisés chaque saison. Les transferts sont en général réservables en amont via votre hébergement.',
    rentCarLabel: 'Louer une voiture · EconomyBookings',
    sampleItinerary: 'Exemple de programme',
    dayPlanH2: (n: number, name: string) => `Un programme de ${n} jours à ${name}`,
    dayPlanLead: 'La trame d\'un voyage type en saison des aurores. Ajustez selon votre niveau, ce sont des points de départ, pas des prescriptions.',
    moreLapland: 'Plus de Laponie',
    otherDestinations: 'Autres destinations',
    seeStays: 'Voir les hébergements',
    finnishLapland: 'Laponie finlandaise',
    readMore: "Découvrir en Laponie",
    planTripEyebrow: "Au-delà du séjour",
    planTripH2: "Planifier tout le voyage",
    planActivities: "Activités",
    planTransfers: "Transferts",
    planCarRental: "Location de voiture",
  }

export default copy