import type { Copy } from './DestinationPage.copy.types'

const copy: Copy = {
    breadcrumbHome: 'Inicio',
    overviewEyebrow: 'Resumen',
    overviewH2: (n: string) => `Por qué alojarse en ${n}`,
    seePricesIn: (n: string) => `Ver precios en ${n}`,
    highlightsEyebrow: 'Lo que lo hace especial',
    highlightsH2: (n: string) => `Lo destacado de ${n}`,
    whenToGoEyebrow: 'Cuándo ir',
    seasonsH3: 'Temporadas',
    gettingThereEyebrow: 'Cómo llegar',
    travelH3: 'Viajar',
    staysInEyebrow: (n: string) => `Alojamiento en ${n}`,
    whatToBookH2: 'Qué reservar',
    findCabinH3: (n: string) => `Encuentre su cabaña en ${n}`,
    findCabinLead: 'Compruebe disponibilidad y compare tarifas, sin comisiones de intermediario.',
    checkAvailability: 'Ver disponibilidad',
    anchorEyebrow: 'Alojamientos ancla',
    whereToStayH2: (n: string) => `Dónde alojarse en ${n}`,
    anchorLead: 'Haga clic para ver tarifas actualizadas en Trip.com. Los alojamientos se reservan 4–8 meses antes en temporada alta.',
    gettingThereH2: (n: string) => `Cómo llegar a ${n}`,
    transportLead: 'Tarifas reales de las páginas de los operadores, reverificadas estacionalmente. Los traslados suelen prereservarse a través del alojamiento.',
    rentCarLabel: 'Alquilar coche · EconomyBookings',
    sampleItinerary: 'Itinerario tipo',
    dayPlanH2: (n: number, name: string) => `Plan de ${n} días en ${name}`,
    dayPlanLead: 'La forma de un viaje típico en temporada de aurora. Ajuste por nivel, son puntos de partida, no recetas.',
    moreLapland: 'Más Laponia',
    otherDestinations: 'Otros destinos',
    seeStays: 'Ver alojamientos',
    finnishLapland: 'Laponia finlandesa',
    readMore: "Descubrir en Laponia",
    planTripEyebrow: "Más allá del alojamiento",
    planTripH2: "Planifique todo el viaje",
    planActivities: "Actividades",
    planSkiResorts: "Estaciones de esquí",
    planTransfers: "Traslados",
    planCarRental: "Alquiler de coches",
  }

export default copy